import { useEffect, useState } from "react";
import { bikePath, catalog, money, publishedPrice, modelSources, type CatalogBike } from "../catalog";
import { useApp } from "../state";
import { monthlyPayment } from "../tools";
import BikeTile, { BikeImage } from "../components/BikeTile";
import { Breadcrumbs, PageMeta, ShareButton, SourceNote } from "../components/PageUI";
import Icon from "../components/icons";
import { helmets } from "../resources";
import HelmetTile from "../components/HelmetTile";
import SourceReferences from "../components/SourceReferences";
import { modelTopics } from "./ModelResearchPage";
import { modelFamilies } from "../model-history";
import { colorById } from "../color-records";

export default function BikeDetailPage({ bike }: { bike: CatalogBike }) {
  const { savedIds, toggleSaved, compareIds, toggleCompare, recordView } = useApp();
  const [trim, setTrim] = useState("standard");
  const [down, setDown] = useState(20);
  const [months, setMonths] = useState(36);
  const [inseam, setInseam] = useState(76);
  const isAerox = bike.id === "yamaha-aerox-v3";
  const price = isAerox && trim === "sp" ? bike.priceTo! : bike.priceFrom;
  const payment = monthlyPayment(price * (1 - down / 100), 12, months);
  const related = catalog.filter((item) => item.id !== bike.id && item.transmission === bike.transmission).sort((a, b) => Math.abs(a.priceFrom - bike.priceFrom) - Math.abs(b.priceFrom - bike.priceFrom)).slice(0, 3);
  useEffect(() => { recordView(bike.id); }, [bike.id, recordView]);
  const saved = savedIds.includes(bike.id);
  const compared = compareIds.includes(bike.id);
  const family = modelFamilies.find((item) => item.currentIds.includes(bike.id));

  return <div className="inner-page model-page"><div className="page-container">
    <PageMeta title={`${bike.brand} ${bike.model}: price, specs and ownership`} description={`${bike.brand} ${bike.model} published price from ${money(bike.priceFrom)}. Compare specifications, check your fit and estimate financing with transparent assumptions.`} />
    <Breadcrumbs items={[{ label: "Motorcycles", href: "/motorcycles" }, { label: bike.brand, href: `/motorcycles/${bike.slug?.split("/")[0] || bike.brand.toLowerCase()}` }, { label: bike.model }]} />
    <section className="model-overview" id="overview"><div className="model-visual"><BikeImage bike={bike} eager /><p>Reference image. Confirm the exact Philippine variant and color.</p></div><div className="model-heading"><p className="page-eyebrow">{bike.brand} / {bike.category[0]}</p><h1>{bike.model}</h1><p className="model-summary">{bike.note || `${bike.cc} cc, ${bike.transmission.toLowerCase()} transmission and a ${bike.seat} mm seat. Start with the published facts, then check the fit and the complete cost.`}</p><div className="model-price"><span>Published Philippine price</span><strong>{isAerox ? money(price) : publishedPrice(bike)}</strong><small>Source dated {bike.checked}. Confirm the current dealer quote.</small></div>
      {isAerox && <fieldset className="model-variants"><legend>Explore a configuration</legend><label className={trim === "standard" ? "selected" : ""}><input type="radio" name="trim" checked={trim === "standard"} onChange={() => setTrim("standard")} />Standard<span>{money(bike.priceFrom)}</span></label><label className={trim === "sp" ? "selected" : ""}><input type="radio" name="trim" checked={trim === "sp"} onChange={() => setTrim("sp")} />SP<span>{money(bike.priceTo!)}</span></label></fieldset>}
      <div className="model-actions"><button type="button" className="action-primary" onClick={() => toggleCompare(bike.id)} aria-pressed={compared}><Icon name={compared ? "check" : "compare"} className="h-4 w-4" />{compared ? "In your comparison" : "Add to comparison"}</button><button type="button" className={`action-secondary ${saved ? "saved-action" : ""}`} onClick={() => toggleSaved(bike.id)} aria-pressed={saved}><Icon name={saved ? "heartFill" : "heart"} className="h-4 w-4" />{saved ? "Saved" : "Save bike"}</button></div><a className="text-link mt-5" href={`/dealers?brand=${encodeURIComponent(bike.brand)}`}><Icon name="pin" className="h-4 w-4" />Find a {bike.brand} dealer<Icon name="arrowRight" className="h-4 w-4" /></a>
    </div></section>
    <nav className="model-section-nav" aria-label="On this model page">{[["specifications", "The specifications"], ["plan", "The monthly picture"], ["fit", "Your fit"], ["alternatives", "Alternatives"]].map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}{colorById.has(bike.id) && <a href={`${bikePath(bike)}/colors`}>Recorded colors</a>}<ShareButton label="Share bike" /></nav>
    <section className="detail-section" id="specifications"><div className="detail-section-heading"><p className="page-eyebrow">The facts first</p><h2>Get to know the numbers.</h2><p>Consistent units, clear evidence and no guessing at missing data.</p></div><dl className="model-specifications">{[["Engine", `${bike.cc} cc`], ["Power", `${bike.hp} hp`], ["Transmission", bike.transmission], ["Seat height", `${bike.seat} mm`], ["Curb weight", bike.weight ? `${bike.weight} kg` : "Not recorded"], ["Fuel tank", bike.tank ? `${bike.tank} L` : "Not recorded"], ["Torque", bike.torque ? `${bike.torque} Nm` : "Not recorded"], ["Front tire", bike.tires?.[0] || "Not recorded"], ["Rear tire", bike.tires?.[1] || "Not recorded"]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><SourceNote>{bike.brakes || "Brake and ABS equipment can vary by local variant. Confirm the exact trim before assuming a particular package."}</SourceNote><a href={`${bikePath(bike)}/specs`} className="text-link">Explore the full specification page<Icon name="arrowRight" className="h-4 w-4" /></a></section>
    <section className="detail-section model-plan" id="plan"><div className="detail-section-heading"><p className="page-eyebrow">Plan before you pay</p><h2>The monthly picture.</h2><p>Change the down payment and term. Take these assumptions into the full planner to include your actual interest rate and fees.</p><a href={`/tools/motorcycle-loan-calculator?bike=${bike.id}&price=${price}&down=${down}&months=${months}&rate=12`} className="text-link mt-5">Open full loan planner<Icon name="arrowRight" className="h-4 w-4" /></a></div><div className="model-plan-controls"><label htmlFor="detail-down">Down payment<strong>{down}% / {money(price * down / 100)}</strong></label><input id="detail-down" type="range" className="ranger" min="10" max="100" step="5" value={down} onChange={(e) => setDown(Number(e.target.value))} /><label htmlFor="detail-term">Loan term</label><select id="detail-term" className="field-input" value={months} onChange={(e) => setMonths(Number(e.target.value))}>{[12, 24, 36, 48].map((term) => <option key={term} value={term}>{term} months</option>)}</select><div className="model-payment"><span>Monthly estimate</span><strong aria-live="polite">{money(payment)}</strong></div><p className="field-help">12% nominal annual interest, diminishing balance. Fees excluded. Total before fees: {money(price * down / 100 + payment * months)}. Not a lender quote.</p></div></section>
    <section className="detail-section model-fit" id="fit"><div className="detail-section-heading"><p className="page-eyebrow">Your comfort matters</p><h2>More than a seat-height number.</h2><p>Seat width, suspension sag, footwear, road camber and technique all change actual foot reach. Always sit on the exact motorcycle.</p><a href={`/fitment?bike=${bike.id}`} className="text-link mt-5">Compare rider fit<Icon name="arrowRight" className="h-4 w-4" /></a></div><div><label className="field-label" htmlFor="detail-inseam">Your inseam: {inseam} cm</label><input id="detail-inseam" className="ranger" type="range" min="55" max="100" value={inseam} onChange={(e) => setInseam(Number(e.target.value))} /><div className="fit-measurements"><div><span>Published seat</span><strong>{bike.seat}<small> mm</small></strong></div><div><span>Seat minus inseam</span><strong>{bike.seat - inseam * 10 > 0 ? "+" : ""}{bike.seat - inseam * 10}<small> mm</small></strong></div></div><p className="field-help">A geometric difference, not a prediction of flat-footing or a safety rating.</p></div></section>
     <section className="detail-section" id="alternatives"><div className="section-line-heading"><div><p className="page-eyebrow">Keep an open shortlist</p><h2>Same conversation. Different rides.</h2></div><a href="/motorcycles" className="text-link">All motorcycles<Icon name="arrowRight" className="h-4 w-4" /></a></div><div className="three-bike-grid">{related.map((item) => <BikeTile key={item.id} bike={item} />)}</div></section>
     <section className="detail-section" id="gear"><div className="section-line-heading"><div><p className="page-eyebrow">Ride with the right lid</p><h2>Helmets to research with this {bike.model}.</h2></div><a href={bike.priceFrom < 100000 ? "/gear/helmets/under-5000" : "/gear/helmets"} className="text-link">Helmet catalog<Icon name="arrowRight" className="h-4 w-4" /></a></div><p className="brand-section-copy">A motorcycle budget is incomplete without a helmet that fits. These are format-matched starting points from the local catalog — not a claim that any helmet is certified or sized for you.</p><div className="brand-model-preview">{helmets.filter((h) => h.price !== null && (bike.priceFrom < 120000 ? h.price <= 8000 : h.price >= 4000)).slice(0, 3).map((h) => <HelmetTile helmet={h} key={h.id} />)}</div><a className="text-link mt-4" href="/guides/first-motorcycle-buying-checklist">First-bike buying checklist<Icon name="arrowRight" className="h-4 w-4" /></a></section>
    <section className="detail-section"><div className="brand-editorial-columns"><div><p className="page-eyebrow">Living with the motorcycle</p><h2>What to check before choosing the {bike.model}.</h2></div><div className="brand-support-copy"><p>The {bike.cc} cc engine and {bike.transmission.toLowerCase()} transmission describe the recorded model, not how every rider will experience it. Compare the controls, parking effort and riding position with your real route and passenger needs.</p><p>A published reference of {publishedPrice(bike)} is not necessarily the complete cash price. Ask for the variant, current quote, fees, registration, warranty and release conditions in writing.</p><p>Use the exact-model service schedule and inspect local parts and service support. Budget for fuel, maintenance, tires, insurance and registration, as well as the finance payment.</p><a href={`/ownership/cost-calculator?bike=${bike.id}`} className="text-link">Build an ownership budget<Icon name="arrowRight" className="h-4 w-4" /></a>{family && <a className="text-link" href={family.path}>Compare {family.name} generations<Icon name="arrowRight" className="h-4 w-4" /></a>}</div></div></section>
    <section className="detail-section"><div className="section-line-heading"><div><p className="page-eyebrow">Go deeper without leaving the index</p><h2>Every part of your {bike.model} research.</h2></div></div><div className="model-topic-links">{Object.entries(modelTopics).map(([topic, item]) => <a key={topic} href={`${bikePath(bike)}/${topic}`}><Icon name={item.icon} className="h-5 w-5" /><div><h3>{item.title}</h3><p>{item.description}</p></div><Icon name="arrowRight" className="h-4 w-4" /></a>)}</div></section>
    <section className="detail-section"><div className="brand-editorial-columns"><div><p className="page-eyebrow">Useful answers</p><h2>{bike.model} questions.</h2></div><div className="brand-faq">{[
      [`How much is the ${bike.brand} ${bike.model}?`, `The published price reference is ${publishedPrice(bike)}, dated ${bike.checked}. Confirm the current local variant, cash price and additional charges with the seller.`],
      ["Is the lowest monthly payment the cheapest deal?", "Not necessarily. Compare down payment, term, rate method, fees and total payable. The full local installment planner shows those inputs explicitly."],
      ["Does the seat-height figure guarantee it will fit me?", "No. Inseam, seat width, suspension sag, footwear and riding technique affect actual reach. Sit on the exact motorcycle and test the controls before buying."],
      ["What if a specification is not recorded?", "It stays marked as missing rather than being inferred from a similar bike. Verify the exact manufacturer record and local variant before relying on it."],
    ].map(([q, a]) => <details key={q}><summary>{q}<Icon name="plus" className="h-4 w-4" /></summary><p>{a}</p></details>)}</div></div></section>
    <SourceReferences sources={modelSources(bike)} note="This model overview and all of its research subpages are rendered locally. Missing specification fields are not filled with estimates. Undated comparison-page references are not manufacturer price guarantees." />
  </div></div>;
}