import { useState } from "react";
import type { ResearchPage } from "../content";
import { collectionModels, type Collection } from "../collections";
import { bikePath, money, publishedPrice } from "../catalog";
import { useApp } from "../state";
import { useQuery } from "../router";
import { PageIntro, PageMeta, ShareButton, SourceNote } from "../components/PageUI";
import BikeTile from "../components/BikeTile";
import SourceReferences from "../components/SourceReferences";
import Icon from "../components/icons";

export default function CollectionPage({ page, definition }: { page: ResearchPage; definition: Collection }) {
  const { bookmarks, toggleBookmark, compareIds, toggleCompare } = useApp();
  const { params, setQuery } = useQuery();
  const [expanded, setExpanded] = useState(false);
  const models = collectionModels(definition);
  const query = params.get("q") || "";
  const filtered = models.filter((bike) => `${bike.brand} ${bike.model}`.toLowerCase().includes(query.toLowerCase()));
  const shown = expanded ? filtered : filtered.slice(0, 6);
  const saved = bookmarks.includes(page.href);
  const comparisonMetric = definition.order === "economy" ? "Published economy" : definition.order === "weight" ? "Curb weight" : definition.order === "tank" ? "Fuel tank" : "Transmission";
  const helperText = page.href.includes("with-abs") ? "ABS is listed on at least one variant of each included model. Check the exact trim; the brake notes below are not a guarantee for every dealer unit." : "The criteria are deliberately visible. This is a current reference-record shortlist, not a paid ranking or a guarantee of stock, fit or safety.";

  return <div className="inner-page collection-page"><div className="page-container"><PageMeta title={`${page.title} | Prices, shortlist and buying guide`} description={page.desc} /><PageIntro eyebrow={page.href.startsWith("/commute") ? "Built for the everyday" : "The MotoIndex buying guide"} title={page.title} description={page.desc} breadcrumbs={[{ label: "Buying guides", href: "/recommendations" }, { label: page.title }]} action={<button type="button" className="action-secondary" aria-pressed={saved} onClick={() => toggleBookmark(page.href)}><Icon name={saved ? "heartFill" : "heart"} className="h-4 w-4" />{saved ? "Guide saved" : "Save this guide"}</button>} />
    <nav className="brand-section-nav" aria-label="Buying guide sections"><a href="#selection">Selection criteria</a><a href="#shortlist">The shortlist</a><a href="#price-comparison">Price comparison</a><a href="#buying-advice">What to consider</a><a href="#collection-faq">Questions</a></nav>
    <section id="selection" className="collection-criteria"><div><p className="page-eyebrow">No mystery rankings</p><h2>Here is how this shortlist is built.</h2><p>{helperText}</p></div><ol>{definition.criteria.map((criterion, index) => <li key={criterion}><span>0{index + 1}</span>{criterion}</li>)}</ol></section>
    <section id="shortlist" className="detail-section"><div className="section-line-heading"><div><p className="page-eyebrow">From research to possibilities</p><h2>{models.length} models, with the facts in view.</h2></div><ShareButton label="Share this guide" /></div><div className="collection-search"><Icon name="search" className="h-4 w-4" /><input type="search" aria-label="Search models in this shortlist" placeholder="Search within this shortlist..." value={query} onChange={(event) => setQuery({ q: event.target.value || undefined })} /><span aria-live="polite">{filtered.length} matches</span></div><div className="collection-model-grid">{shown.map((bike) => <BikeTile bike={bike} key={bike.id} />)}</div>{!filtered.length && <div className="empty-state"><h2>No models match that search.</h2><p>Try another model name or clear your search.</p><button type="button" className="action-primary" onClick={() => setQuery({ q: undefined })}>Clear search</button></div>}{filtered.length > 6 && <button type="button" className="action-secondary collection-expand" onClick={() => setExpanded(!expanded)}>{expanded ? "Show the first six models" : `Show all ${filtered.length} models`}<Icon name="chevronDown" className={`h-4 w-4 ${expanded ? "rotate-180" : ""}`} /></button>}</section>
    <section className="detail-section" id="price-comparison"><div className="section-line-heading"><h2>Compare the important numbers.</h2><span>Published references, not quotes</span></div><div className="brand-price-table-wrap" role="region" tabIndex={0} aria-label="Shortlist price comparison, scroll horizontally on small screens"><table className="brand-price-table"><caption className="sr-only">Specifications and published prices for this shortlist</caption><thead><tr><th scope="col">Model</th><th scope="col">Price reference</th><th scope="col">Engine</th><th scope="col">Seat</th><th scope="col">{comparisonMetric}</th><th scope="col">Compare</th></tr></thead><tbody>{filtered.map((bike) => <tr key={bike.id}><th scope="row"><a href={bikePath(bike)}>{bike.brand} {bike.model}</a>{page.href.includes("with-abs") && <small>{bike.brakes}</small>}</th><td>{publishedPrice(bike)}<small>Source date: {bike.checked}</small></td><td>{bike.cc} cc</td><td>{bike.seat} mm</td><td>{definition.order === "economy" ? `${bike.economy} km/L` : definition.order === "weight" ? `${bike.weight} kg` : definition.order === "tank" ? `${bike.tank} L` : bike.transmission}</td><td><button type="button" className="brand-table-compare" aria-pressed={compareIds.includes(bike.id)} onClick={() => toggleCompare(bike.id)}><Icon name={compareIds.includes(bike.id) ? "check" : "plus"} className="h-4 w-4" />{compareIds.includes(bike.id) ? "Added" : "Add"}</button></td></tr>)}</tbody></table></div></section>
    <section className="detail-section" id="buying-advice"><div className="brand-editorial-columns"><div><p className="page-eyebrow">The decision behind the data</p><h2>A good shortlist is only the beginning.</h2><a href={definition.next} className="text-link mt-5">Take the next planning step<Icon name="arrowRight" className="h-4 w-4" /></a></div><div className="brand-buying-steps">{definition.paragraphs.map((section, index) => <div key={section.title}><span>0{index + 1}</span><div><h3>{section.title}</h3><p>{section.text}</p></div></div>)}</div></div></section>
    <section className="detail-section" id="collection-faq"><div className="brand-editorial-columns"><div><p className="page-eyebrow">Before the showroom</p><h2>Your shortlist questions, answered.</h2></div><div className="brand-faq">{[
      ["Does being listed here make a motorcycle the best choice for me?", "No. It means the model matches the stated record-based criteria. Your physical fit, experience, local roads, load and service support still matter. Arrange an in-person check before buying."],
      ["Do the published prices include registration and financing?", "Do not assume they do. Price references and ranges can describe different variants or observations. Ask the seller for an itemized, current quotation and compare the same exact configuration."],
      ["Are models with missing specifications ranked as zero?", "No. Weight, tank-capacity and economy collections require the corresponding recorded figure. Missing values are excluded when that field is part of the rule. A planning estimate is not used as a published economy result."],
      ["What is the starting price in this record set?", models.length ? `The lowest recorded starting price among matching models is ${money(Math.min(...models.map((bike) => bike.priceFrom)))}. That is a dated reference, not a live inventory offer or a promise of the final price.` : "No current record matches the listed criteria. Broaden the research rather than assuming an unrecorded price."],
    ].map(([q, a]) => <details key={q}><summary>{q}<Icon name="plus" className="h-4 w-4" /></summary><p>{a}</p></details>)}</div></div></section>
    <SourceNote>This page applies its disclosed criteria to the locally available model records. Source coverage may be narrower than the complete market. All model, comparison and planning links open pages in this application.</SourceNote><SourceReferences sources={definition.sources || [{ label: "Original MotoIndex research reference", href: `https://motoindexph.com${page.href}` }]} note="Sources support the model facts. Selection criteria, the local price table and editorial guidance are shown on this page; source coverage is not a claim about all models on the market." />
  </div></div>;
}