import { useState } from "react";
import { bikePath, type CatalogBike } from "../catalog";
import type { ColorRecord } from "../color-records";
import { useApp } from "../state";
import { writeStored, readStored } from "../utils/storage";
import { PageIntro, PageMeta, SourceNote } from "../components/PageUI";
import SourceReferences from "../components/SourceReferences";
import { BikeImage } from "../components/BikeTile";
import Icon from "../components/icons";

export default function ColorsPage({ bike, record }: { bike: CatalogBike; record: ColorRecord }) {
  const { notify } = useApp();
  const [selected, setSelected] = useState(() => { const stored = readStored<unknown>(`color:${bike.id}`, ""); return record.colors.find((color) => color.name === stored)?.name || record.colors[0].name; });
  const color = record.colors.find((item) => item.name === selected)!;
  const save = () => { const success = writeStored(`color:${bike.id}`, selected); notify(success ? `${selected} saved as your research preference. Stock is not confirmed.` : "Preference selected for this session; storage is unavailable.", success ? "dark" : "red"); };
  return <div className="inner-page"><div className="page-container">
    <PageMeta title={`${bike.brand} ${bike.model} colors Philippines: names and variant checks`} description={`Recorded ${bike.model} finishes: ${record.colors.map((item) => item.name).join(", ")}. Confirm the exact local year, variant and seller inventory.`} />
    <PageIntro eyebrow="The model color guide" title={`${bike.model}. Know the finish before you reserve.`} description="Published color names, with variant context where recorded. No guessed paint swatches or silently recolored product photos." breadcrumbs={[{ label: bike.brand, href: `/motorcycles/${bike.slug?.split("/")[0]}` }, { label: bike.model, href: bikePath(bike) }, { label: "Colors" }]} />
    <div className="color-guide-layout"><div className="color-guide-photo"><BikeImage bike={bike} eager /><p>Reference model image only. It does not change to represent the selected color.</p></div><section className="color-guide-options"><p className="page-eyebrow">{record.colors.length} recorded finishes</p><h2>Choose a name to check with the dealer.</h2><fieldset><legend className="sr-only">Recorded color preference</legend>{record.colors.map((item) => <label key={item.name} className={item.name === selected ? "selected" : ""}><input type="radio" name="model-color" value={item.name} checked={selected === item.name} onChange={() => setSelected(item.name)} /><span><strong>{item.name}</strong><small>{item.variant ? `${item.variant} reference configuration` : "Exact year and trim availability to be confirmed"}</small></span></label>)}</fieldset><button className="action-primary" type="button" onClick={save}><Icon name="heart" className="h-4 w-4" />Save color preference</button><p className="field-help">Selected: {selected}. {color.variant ? `Recorded on ${color.variant}; verify the actual unit.` : "No trim-specific assignment is recorded."}</p></section></div>
    <section className="detail-section brand-editorial-columns"><div><p className="page-eyebrow">Names, not inventory promises</p><h2>Keep color, generation and trim together.</h2></div><div className="brand-support-copy"><p>The source record was checked on {record.checked}. Dealer inventory, graphics and model-year color names can change. These labels do not prove every finish is available on every variant.</p><p>Ask the branch to put the exact model, variant and finish on a written quotation. Inspect the actual unit under ordinary lighting before deciding; screens, camera processing and compression can change its appearance.</p><a className="text-link" href={`/dealers?brand=${encodeURIComponent(bike.brand)}`}>Find a dealer to confirm the finish<Icon name="arrowRight" className="h-4 w-4" /></a></div></section>
    <section className="detail-section"><div className="brand-editorial-columns"><div><p className="page-eyebrow">Good questions</p><h2>{bike.model} color FAQs.</h2></div><div className="brand-faq">{[[`What colors are recorded for ${bike.model}?`, record.colors.map((item) => item.name).join(", ") + ". These are dated names, not a live stock feed."], ["Are all colors offered on every trim?", "Not necessarily. Where variant mapping is recorded it is shown explicitly. Otherwise, ask the seller to confirm the exact local model year and trim."], ["Does the photo show my selected paint?", "No. The reference photograph is not recolored, and no digital swatch is claimed to match the paint. Inspect the actual finish before paying."], ["Does saving a color reserve a motorcycle?", "No. It only stores a research preference in this browser. It does not contact a dealer, confirm inventory or create a reservation."]].map(([q, a]) => <details key={q}><summary>{q}<Icon name="plus" className="h-4 w-4" /></summary><p>{a}</p></details>)}</div></div></section>
    <SourceNote>This restores an existing model-color intent locally. It does not create separate duplicate pages for color spellings or unverified generation labels.</SourceNote><SourceReferences sources={record.sources} />
  </div></div>;
}