import { useState } from "react";
import { catalog, money } from "../catalog";
import { useQuery } from "../router";
import { PageIntro, PageMeta, SourceNote, EmptyState } from "../components/PageUI";
import BikeTile from "../components/BikeTile";
import Icon from "../components/icons";

export default function FinderPage({ fitOnly = false }: { fitOnly?: boolean }) {
  const { params } = useQuery();
  const [step, setStep] = useState(0);
  const [budget, setBudget] = useState(175000);
  const [purpose, setPurpose] = useState("Commuter");
  const [transmission, setTransmission] = useState("Any");
  const [inseam, setInseam] = useState(76);
  const [result, setResult] = useState(false);
  const [fitBike, setFitBike] = useState(params.get("bike") || catalog[0].id);
  const selectedBike = catalog.find((bike) => bike.id === fitBike) || catalog[0];
  const eligible = catalog.filter((bike) => bike.priceFrom <= budget && (transmission === "Any" || bike.transmission === transmission));
  const results = eligible.sort((a, b) => Number(b.category.includes(purpose as never)) - Number(a.category.includes(purpose as never)) || Math.abs(a.seat - inseam * 10) - Math.abs(b.seat - inseam * 10)).slice(0, 3);
  const steps = ["Budget", "Your riding", "Controls", "Rider fit"];

  return <div className="inner-page"><div className="page-container"><PageMeta title={fitOnly ? "Motorcycle rider fitment check" : "Find my motorcycle match"} description="Find a practical motorcycle shortlist using your budget, riding purpose, transmission preference and published seat-height context." /><PageIntro eyebrow={fitOnly ? "Rider fitment check" : "Find my match"} title={fitOnly ? "Find your feet. Then find your ride." : "Start with your life. Not a list."} description={fitOnly ? "A dimensional starting point, not a fit guarantee. Check the numbers, then sit on the exact bike." : "A few thoughtful questions. A transparent shortlist. No mysterious match scores or paid rankings."} />
    {fitOnly ? <div className="fit-page-layout"><div className="fit-form"><label className="field-label" htmlFor="fit-bike">Choose your motorcycle</label><select className="field-input" id="fit-bike" value={fitBike} onChange={(e) => setFitBike(e.target.value)}>{catalog.map((bike) => <option value={bike.id} key={bike.id}>{bike.brand} {bike.model}</option>)}</select><label className="field-label mt-8" htmlFor="fit-inseam">Your inseam: {inseam} cm</label><input className="ranger" id="fit-inseam" type="range" min="55" max="100" value={inseam} onChange={(e) => setInseam(Number(e.target.value))} /><div className="fit-measurements"><div><span>Published seat</span><strong>{selectedBike.seat}<small> mm</small></strong></div><div><span>Seat minus inseam</span><strong>{selectedBike.seat - inseam * 10 > 0 ? "+" : ""}{selectedBike.seat - inseam * 10}<small> mm</small></strong></div></div><SourceNote>Seat width, sag, footwear and riding technique are not captured here. A positive or negative difference does not prove that you can flat-foot, or that this bike is safer for you.</SourceNote><a className="text-link mt-5" href="/recommendations/best-motorcycles-for-short-riders">Explore the lower-seat guide<Icon name="arrowRight" className="h-4 w-4" /></a></div><BikeTile bike={selectedBike} /></div> : <>
      {!result ? <div className="finder-panel"><aside className="finder-story"><p className="page-eyebrow">Built around you</p><h2>The right bike fits the everyday.</h2><p>A weekday commute and a weekend ride do not ask the same things of a motorcycle. Tell us what matters.</p><ol>{steps.map((label, i) => <li className={step === i ? "current" : step > i ? "complete" : ""} key={label}><span>{step > i ? <Icon name="check" className="h-4 w-4" /> : `0${i + 1}`}</span>{label}</li>)}</ol><small>Your answers stay in this session. No email required.</small></aside><section className="finder-question" key={step}><p className="page-eyebrow">Question {step + 1} of 4</p>
        {step === 0 && <><h2>Where is your budget comfortable?</h2><p>Start with a purchase-price ceiling. Remember to reserve a separate budget for gear and ownership.</p><output className="finder-budget" htmlFor="finder-budget">{money(budget)}</output><input id="finder-budget" className="ranger" type="range" min="50000" max="500000" step="5000" value={budget} onChange={(e) => setBudget(Number(e.target.value))} /><div className="range-captions"><span>PHP 50,000</span><span>PHP 500,000</span></div></>}
        {step === 1 && <><h2>What does your everyday ride look like?</h2><p>We will prioritize that category, then show alternatives if none fit your hard constraints.</p><div className="finder-options">{[["Commuter", "City commuting", "Stop-and-go traffic and daily errands.", "route"], ["Adventure", "Longer roads", "Provincial trips and varied surfaces.", "adventure"], ["Sport", "Weekend sport", "Road-focused, engaged riding.", "sport"], ["Off-road", "Off the pavement", "Trails and rougher roads.", "offroad"]].map(([key, title, sub, icon]) => <button className={purpose === key ? "selected" : ""} type="button" key={key} aria-pressed={purpose === key} onClick={() => setPurpose(key)}><Icon name={icon} className="h-6 w-6" /><strong>{title}</strong><small>{sub}</small></button>)}</div></>}
        {step === 2 && <><h2>How do you like to ride?</h2><p>Transmission is a hard filter: we will not recommend a manual if you choose automatic.</p><div className="finder-options single-column">{[["Automatic", "Twist and go. No clutch lever."], ["Manual", "Gear changes and clutch control."], ["Any", "Keep my options open."]].map(([key, text]) => <button key={key} className={transmission === key ? "selected" : ""} type="button" aria-pressed={transmission === key} onClick={() => setTransmission(key)}><strong>{key === "Any" ? "No preference" : key}</strong><small>{text}</small></button>)}</div></>}
        {step === 3 && <><h2>What is your inseam?</h2><p>Measure your inner leg to the floor. This helps us order the shortlist by a simple seat-height difference, not predict fit.</p><output className="finder-budget" htmlFor="finder-inseam">{inseam}<span> cm</span></output><input id="finder-inseam" type="range" className="ranger" min="55" max="100" value={inseam} onChange={(e) => setInseam(Number(e.target.value))} /><SourceNote>A sit-on check matters more than this number. Seat shape, suspension sag and footwear change actual reach.</SourceNote></>}
        <div className="finder-step-actions"><button type="button" className="action-secondary" disabled={step === 0} onClick={() => setStep(step - 1)}>Back</button><button type="button" className="action-primary" onClick={() => step < 3 ? setStep(step + 1) : setResult(true)}>{step === 3 ? "See my shortlist" : "Continue"}<Icon name="arrowRight" className="h-4 w-4" /></button></div>
      </section></div> : <section className="finder-results"><div className="section-line-heading"><div><p className="page-eyebrow">Your starting shortlist</p><h2>{results.length ? "A few rides worth a closer look." : "Your constraints come first."}</h2><p>Under {money(budget)} / {transmission === "Any" ? "Any transmission" : transmission} / {inseam} cm inseam</p></div><button type="button" className="action-secondary" onClick={() => { setResult(false); setStep(0); }}>Edit my answers</button></div>{results.length ? <div className="three-bike-grid">{results.map((bike) => <div key={bike.id}><BikeTile bike={bike} /><p className="match-reason"><Icon name="check" className="h-4 w-4 text-racer-500" />Within budget{bike.category.includes(purpose as never) ? ", matches your riding category" : "; alternative category"}. Seat difference: {bike.seat - inseam * 10} mm.</p></div>)}</div> : <EmptyState title="No exact matches in this preview." text="We will not quietly exceed your budget or transmission preference. Edit your answers or explore the broader catalog." /> }<SourceNote>Suggestions use the {catalog.length} imported reference models. Budget and transmission are hard limits; category and seat-height proximity determine ordering. No paid ranking or unverified percentage score.</SourceNote></section>}
    </>}
  </div></div>;
}