import { useState } from "react";
import { helmets, type Helmet } from "../resources";
import { useApp } from "../state";
import { HelmetImage, helmetPrice } from "../components/HelmetTile";
import HelmetTile from "../components/HelmetTile";
import ShopButtons from "../components/ShopButtons";
import AffiliateDisclosure from "../components/AffiliateDisclosure";
import { PageMeta, Breadcrumbs, ShareButton, SourceNote } from "../components/PageUI";
import SourceReferences from "../components/SourceReferences";
import { helmetShopQuery, OFFICIAL_STORES } from "../affiliate";
import { readStored, writeStored } from "../utils/storage";
import Icon from "../components/icons";

const fitChecks = ["Used the size chart for the exact helmet model.", "Crown is snug and evenly supported, without a painful pressure point.", "Cheek pads make contact and the skin moves with the helmet.", "The helmet does not rotate freely around the head.", "Retention strap fastens securely.", "Applicable PS/ICC and certification markings checked on the actual unit."];

export default function HelmetDetails({ helmet }: { helmet: Helmet }) {
  const { bookmarks, toggleBookmark, notify } = useApp();
  const path = `/gear/helmets/${helmet.slug}`;
  const storageKey = `helmet-fit:${helmet.id}`;
  const [checked, setChecked] = useState<string[]>(() => { const stored = readStored<unknown>(storageKey, []); return Array.isArray(stored) ? stored.filter((v): v is string => typeof v === "string") : []; });
  const [measurement, setMeasurement] = useState("");
  const saved = bookmarks.includes(path);
  const alternatives = helmets.filter((h) => h.id !== helmet.id && h.type === helmet.type).slice(0, 3);
  const shopQuery = helmetShopQuery(helmet.brand, helmet.model);
  const officialStore = OFFICIAL_STORES.find((s) => s.brand.toLowerCase() === helmet.brand.toLowerCase());
  const toggleCheck = (item: string) => { const next = checked.includes(item) ? checked.filter((v) => v !== item) : [...checked, item]; setChecked(next); if (!writeStored(storageKey, next)) notify("Fit checklist is available for this session only", "red"); };
  const advice = helmet.type === "Modular" ? "Check the manufacturer's riding position and chin-bar locking instructions for this exact model. A flip-up mechanism is not permission to assume identical certification in every configuration." : helmet.type === "Open face" ? "An open-face format does not provide the chin coverage of a full-face shell. Consider the actual protection format, riding use and fit rather than treating airflow and price as the only criteria." : "A full-face label describes the format, not the exact certification, internal shape or fit. Inspect the unit, retention system, visor arrangement and size chart before deciding.";

  return <div className="inner-page"><div className="page-container"><PageMeta title={`${helmet.brand} ${helmet.model}: price, fit and buying guide`} description={`A local buying guide for the ${helmet.brand} ${helmet.model}, including recorded pricing, format, sizes, an interactive fit checklist and exact-unit certification checks.`} /><Breadcrumbs items={[{ label: "Helmets", href: "/gear/helmets" }, { label: helmet.brand, href: `/gear/helmets/${helmet.brand.toLowerCase()}` }, { label: helmet.model }]} /><div className="helmet-detail"><div className="helmet-detail-photo"><HelmetImage helmet={helmet} /></div><div><p className="page-eyebrow">{helmet.brand} / {helmet.type}</p><h1>{helmet.model}</h1><p className="page-description">Get to know the model, then make the fit personal. Price, labels and a familiar brand cannot replace checking the helmet you will actually wear.</p><div className="model-price"><span>{helmet.price === null ? "Published price evidence" : "Published starting-price reference"}</span><strong>{helmetPrice(helmet)}</strong><small>{helmet.price === null ? "No priced record is attached. Do not interpret this as free or unavailable." : "Graphics, sizes, visor bundles, stock and seller offers can change the price."}</small></div><div className="model-actions"><button type="button" className="action-primary" aria-pressed={saved} onClick={() => toggleBookmark(path)}><Icon name={saved ? "check" : "heart"} className="h-4 w-4" />{saved ? "Saved to your garage" : "Save this helmet"}</button><a href={`/gear/helmets/compare?models=${helmet.id}`} className="action-secondary"><Icon name="compare" className="h-4 w-4" />Compare helmet</a><ShareButton /></div><div className="hero-shop"><p>Ready to buy? Compare live seller prices:</p><ShopButtons productKey={helmet.id} query={shopQuery} label={`${helmet.brand} ${helmet.model}`} layout="compact" /></div></div></div>
    <nav className="model-section-nav" aria-label="Helmet detail sections"><a href="#helmet-details">Model details</a><a href="#where-to-buy">Where to buy</a><a href="#helmet-fit">Fit checklist</a><a href="#helmet-certification">Certification</a><a href="#helmet-ownership">Care & spares</a><a href="#helmet-faq">FAQs</a></nav>
    <section className="detail-section" id="helmet-details"><div className="detail-section-heading"><p className="page-eyebrow">The product record</p><h2>What is recorded, and what to verify.</h2><p>{advice}</p></div><dl className="model-specifications">{[["Format", helmet.type], ["Recorded sizes", helmet.sizes || "Model chart not recorded"], ["Published price", helmetPrice(helmet)], ["Shell material", "Not recorded; confirm exact variant"], ["Certification", "Inspect labels on the actual local unit"], ["Visor / intercom", "Check exact-model equipment"]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><SourceNote>Missing attributes are not inferred from another helmet in the brand. Keep seller observations, certification evidence and personal fit separate.</SourceNote></section>
    <section className="detail-section" id="where-to-buy"><div className="detail-section-heading"><p className="page-eyebrow">Where to buy</p><h2>Compare live prices on Shopee & Lazada.</h2><p>Our recorded reference is {helmetPrice(helmet)}. Live seller prices change daily — check both platforms and prefer official or highly-rated sellers.</p></div><ShopButtons productKey={helmet.id} query={shopQuery} label={`${helmet.brand} ${helmet.model}`} layout="full" />{officialStore && <a className="official-store-link" href={officialStore.href} target="_blank" rel="sponsored nofollow noopener"><Icon name="shield" className="h-4 w-4" />{officialStore.label}<Icon name="external" className="h-3.5 w-3.5" /></a>}<ul className="shop-tips"><li><Icon name="check" className="h-4 w-4" />Match the exact model name, size and graphic — similar listings are often different variants.</li><li><Icon name="check" className="h-4 w-4" />Check seller rating, sold count and return policy before paying.</li><li><Icon name="check" className="h-4 w-4" />On arrival, verify PS/ICC markings and test the fit before removing tags.</li></ul><AffiliateDisclosure compact /></section>
    <section className="detail-section" id="helmet-fit"><div className="brand-editorial-columns"><div><p className="page-eyebrow">Take your time with this part</p><h2>A good fit is more than a letter size.</h2><p className="brand-section-copy">Measure your head using the maker's instructions, compare with the model's chart and try it on when possible. A pressure point can be a head-shape mismatch, not simply a reason to choose a larger size.</p><label className="field-label" htmlFor="helmet-measurement">Your measured circumference (cm)</label><input className="field-input" id="helmet-measurement" type="number" min="40" max="80" step="0.1" value={measurement} onChange={(e) => setMeasurement(e.target.value)} placeholder="Enter your measurement" /><p className="field-help">{measurement && Number(measurement) >= 40 && Number(measurement) <= 80 ? `Compare your ${measurement} cm measurement against the exact ${helmet.model} chart. We do not infer a size from a universal brand chart.` : "No universal size recommendation is calculated. Use the exact model chart."}</p><a className="text-link mt-4" href="/guides/motorcycle-helmet-size-guide">Read the full measuring & fit guide<Icon name="arrowRight" className="h-4 w-4" /></a></div><fieldset className="article-checklist"><legend>Your fit-check progress: {checked.filter((v) => fitChecks.includes(v)).length} / {fitChecks.length}</legend>{fitChecks.map((item) => <label key={item}><input type="checkbox" checked={checked.includes(item)} onChange={() => toggleCheck(item)} /><span>{item}</span></label>)}</fieldset></div></section>
    <section className="detail-section brand-editorial-columns" id="helmet-certification"><div><p className="page-eyebrow">Check the actual unit</p><h2>Certification is not a brand-wide assumption.</h2></div><div className="brand-support-copy"><p>Inspect the applicable Philippine PS or ICC conformity marking and the actual certification label. Different markets, variants and batches can differ. A seller badge or photo of another unit is not enough.</p><p>International homologation, such as an explicit ECE claim, is a separate evidence check. Do not treat a brand name or price as a guarantee of certification or protection.</p><a className="text-link" href="/guides/motorcycle-helmet-certification-philippines">Read the complete Philippine certification guide<Icon name="arrowRight" className="h-4 w-4" /></a></div></section>
    <section className="detail-section brand-editorial-columns" id="helmet-ownership"><div><p className="page-eyebrow">Think beyond unboxing</p><h2>Care, parts and the right replacement advice.</h2></div><div className="brand-support-copy"><p>Check availability of the correct visor, cheek pads, liner and retention-system parts for {helmet.brand} {helmet.model}. A similar-looking visor may have a different locking mechanism or mounting interface.</p><p>Follow the manufacturer cleaning, storage, inspection and replacement instructions. Do not modify the protective shell or liner to accommodate an intercom. Seek manufacturer guidance after an impact; visible appearance alone cannot confirm protective condition.</p><p>When ordering online, confirm exchange terms before removing tags or protective film. Inspect the exact unit and its accessories on arrival.</p></div></section>
    <section className="detail-section" id="helmet-faq"><div className="brand-editorial-columns"><div><p className="page-eyebrow">The practical questions</p><h2>{helmet.model} FAQs.</h2></div><div className="brand-faq">{[["Will my usual helmet size fit?", "Not necessarily. Shell shape and padding differ by model. Use the exact chart and test crown, cheek and retention fit."], ["Is this an official seller offer?", "No. A published reference is not a guarantee of current price, stock, delivery or included accessories."], ["Can I choose it by certification alone?", "Certification and conformity matter, but the actual fit, retention and condition remain essential. Inspect the local unit."], ["How can I compare it with another model?", "Use the local helmet comparison tool to line up price, format and recorded sizes. Then try the actual shortlisted models in person where possible."]].map(([q, a]) => <details key={q}><summary>{q}<Icon name="plus" className="h-4 w-4" /></summary><p>{a}</p></details>)}</div></div></section>
    <section className="detail-section"><div className="section-line-heading"><h2>Other {helmet.type.toLowerCase()} models to research.</h2><a href="/gear/helmets" className="text-link">All helmets<Icon name="arrowRight" className="h-4 w-4" /></a></div><div className="brand-model-preview">{alternatives.map((h) => <HelmetTile helmet={h} key={h.id} />)}</div></section><SourceReferences sources={[{ label: "MotoIndex exact-model reference", href: `https://motoindexph.com${path}` }, { label: "DTI-BPS conformity information", href: "https://bps.dti.gov.ph/product-certification/ps-and-icc-marks" }]} />
    <div className="sticky-shop" role="region" aria-label="Shop this helmet"><span>{helmet.brand} {helmet.model}</span><ShopButtons productKey={helmet.id} query={shopQuery} label={`${helmet.brand} ${helmet.model}`} layout="compact" /></div>
  </div></div>;
}