import { useState } from "react";
import { archivedMotorcycles, type ArchivedMotorcycle, type ModelFamily } from "../model-history";
import { catalogById, bikePath, money, type CatalogBike } from "../catalog";
import { PageIntro, PageMeta, Breadcrumbs, ShareButton, SourceNote } from "../components/PageUI";
import SourceReferences from "../components/SourceReferences";
import BikeTile from "../components/BikeTile";
import { useApp } from "../state";
import { readStored, writeStored } from "../utils/storage";
import Icon from "../components/icons";

export function HistoryImage({ bike }: { bike: ArchivedMotorcycle }) {
  const [failed, setFailed] = useState(false);
  return failed ? <div className="bike-image-placeholder"><Icon name="scooter" className="h-24 w-24" /><span>{bike.name} / historical model</span></div> : <img src={`https://motoindexph.com/media/motorcycles/${bike.id}.webp`} alt={`${bike.brand} ${bike.name}, previous generation`} onError={() => setFailed(true)} loading="lazy" />;
}

export function ArchivePage({ bike }: { bike: ArchivedMotorcycle }) {
  const current = catalogById.get(bike.currentId)!;
  const { bookmarks, toggleBookmark, notify } = useApp();
  const [distance, setDistance] = useState(900);
  const [fuelPrice, setFuelPrice] = useState(65);
  const [economy, setEconomy] = useState(bike.economy);
  const [offer, setOffer] = useState("");
  const [repairs, setRepairs] = useState("0");
  const [transfer, setTransfer] = useState("0");
  const storageKey = `archive-checks:${bike.id}`;
  const [checks, setChecks] = useState<string[]>(() => { const values = readStored<unknown>(storageKey, []); return Array.isArray(values) ? values.filter((value): value is string => typeof value === "string") : []; });
  const fuel = distance / economy * fuelPrice;
  const validOffer = offer.trim() !== "" && [offer, repairs, transfer].every((value) => value.trim() !== "" && Number.isFinite(Number(value)) && Number(value) >= 0 && Number(value) <= 10000000);
  const total = validOffer ? Number(offer) + Number(repairs) + Number(transfer) : 0;
  const saved = bookmarks.includes(bike.path);
  const toggle = (item: string) => { const next = checks.includes(item) ? checks.filter((value) => value !== item) : [...checks, item]; setChecks(next); if (!writeStored(storageKey, next)) notify("Checklist available for this session only", "red"); };

  return <div className="inner-page archive-page"><div className="page-container">
    <PageMeta title={`${bike.brand} ${bike.name}: historical price, specs and used-bike guide`} description={bike.introduction} />
    <Breadcrumbs items={[{ label: "Brands", href: "/brands" }, { label: bike.brand, href: `/motorcycles/${bike.brand.toLowerCase()}` }, { label: bike.name }]} />
    <div className="archive-generation-notice"><span><Icon name="calendar" className="h-4 w-4" />Previous-generation reference</span><a href={bikePath(current)}>Looking for today's {current.model}?<Icon name="arrowRight" className="h-4 w-4" /></a></div>
    <section className="model-overview"><div className="model-visual"><HistoryImage bike={bike} /><p>{bike.generation}. Reference image; confirm the exact unit.</p></div><div className="model-heading"><p className="page-eyebrow">{bike.brand} / Owner & used-bike research</p><h1>{bike.name}</h1><p className="model-summary">{bike.introduction}</p><div className="model-price"><span>Historical launch SRP, not a current asking price</span><strong>{money(bike.historicalPrice)}</strong><small>{bike.priceContext}</small></div><div className="model-actions"><button type="button" className="action-primary" aria-pressed={saved} onClick={() => toggleBookmark(bike.path)}><Icon name={saved ? "check" : "heart"} className="h-4 w-4" />{saved ? "Saved for research" : "Save this model"}</button><ShareButton label="Share model" /></div></div></section>
    <nav className="model-section-nav" aria-label="Archive page sections">{[["history-specs", "Specifications"], ["history-cost", "Running costs"], ["history-used", "Used-bike budget"], ["history-checks", "Buying checks"], ["history-faq", "FAQs"]].map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav>
    <section className="detail-section" id="history-specs"><div className="detail-section-heading"><p className="page-eyebrow">The right generation</p><h2>{bike.name} specifications.</h2><p>Do not transfer these figures to the current {current.model}. Verify the exact year and variant of a used unit.</p></div><dl className="model-specifications">{[["Engine", `${bike.cc} cc`], ["Power", `${bike.hp} hp`], ["Torque", `${bike.torque} Nm`], ["Seat height", `${bike.seat} mm`], ["Curb weight", `${bike.weight} kg`], ["Fuel tank", `${bike.tank} L`], ["Transmission", bike.transmission], ["Front tire", bike.tires[0]], ["Rear tire", bike.tires[1]]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><SourceNote>{bike.brakes} Tire replacement also requires the correct load rating, speed rating, rim and front/rear application.</SourceNote></section>
    <section className="detail-section model-plan" id="history-cost"><div className="detail-section-heading"><p className="page-eyebrow">Your everyday numbers</p><h2>Plan the fuel, not a promise.</h2><p>The starting {bike.economy} km/L figure is {bike.economyIsEstimate ? "a planning estimate, not a manufacturer-published fuel-economy claim" : "a published reference, not a guarantee for your route"}. Traffic, riding style, load and condition change actual consumption.</p><a href={`/ownership/cost-calculator?economy=${economy}&distance=${distance}&fuel=${fuelPrice}`} className="text-link mt-5">Add service, insurance and other costs<Icon name="arrowRight" className="h-4 w-4" /></a></div><div className="model-plan-controls"><label htmlFor="history-distance">Monthly distance<strong>{distance} km</strong></label><input className="ranger" type="range" id="history-distance" min="0" max="4000" step="50" value={distance} onChange={(e) => setDistance(Number(e.target.value))} /><label htmlFor="history-economy">Fuel economy assumption<strong>{economy} km/L</strong></label><input className="ranger" type="range" id="history-economy" min="10" max="80" step="0.1" value={economy} onChange={(e) => setEconomy(Number(e.target.value))} /><label htmlFor="history-fuel">Fuel price<strong>{money(fuelPrice)} / L</strong></label><input className="ranger" type="range" id="history-fuel" min="20" max="150" value={fuelPrice} onChange={(e) => setFuelPrice(Number(e.target.value))} /><div className="model-payment"><span>Estimated fuel per month</span><strong aria-live="polite">{money(fuel)}</strong></div><p className="field-help">Full-tank arithmetic: {Math.round(bike.tank * economy)} km before any reserve. Not a guaranteed usable range.</p></div></section>
    <section className="detail-section model-plan" id="history-used"><div className="detail-section-heading"><p className="page-eyebrow">Look beyond the asking price</p><h2>What will this used bike cost you?</h2><p>Enter a real seller offer and the costs you expect after inspection. The original launch price is not used as an appraisal or a depreciation guarantee.</p><a href="/used-motorcycles/buying-checklist" className="text-link mt-5">Read the complete buyer checklist<Icon name="arrowRight" className="h-4 w-4" /></a></div><div className="model-plan-controls"><div className="used-budget-fields">{[["offer", "Actual seller asking price", offer, setOffer], ["repairs", "Inspection-based repair reserve", repairs, setRepairs], ["transfer", "Transfer and registration budget", transfer, setTransfer]].map(([key, label, value, setter]) => <label key={String(key)}><span>{String(label)}</span><input className="field-input" type="number" min="0" inputMode="decimal" placeholder="Enter your quote" value={String(value)} onChange={(e) => (setter as (value: string) => void)(e.target.value)} /></label>)}</div><div className="model-payment"><span>Initial purchase budget</span><strong aria-live="polite">{validOffer ? money(total) : "Enter a quote"}</strong></div><p className="field-help">Excludes finance charges and ongoing running costs. Inspect documents and the motorcycle before committing.</p></div></section>
    <section className="detail-section" id="history-checks"><div className="brand-editorial-columns"><div><p className="page-eyebrow">Before you buy</p><h2>A few checks worth keeping.</h2><p className="brand-section-copy">A low asking price does not settle the bike's condition, documentary history or the cost of deferred maintenance.</p><a href="/ownership/transfer-of-ownership" className="text-link">Understand ownership transfer<Icon name="arrowRight" className="h-4 w-4" /></a></div><fieldset className="article-checklist"><legend>{bike.name} research checklist</legend>{bike.checkpoints.map((item) => <label key={item}><input type="checkbox" checked={checks.includes(item)} onChange={() => toggle(item)} /><span>{item}</span></label>)}</fieldset></div></section>
    <section className="detail-section" id="history-faq"><div className="brand-editorial-columns"><div><p className="page-eyebrow">Good questions</p><h2>{bike.name} ownership FAQs.</h2></div><div className="brand-faq">{[
      [`Is ${money(bike.historicalPrice)} the current used price?`, "No. It is a historical launch reference. Year, mileage, service history, condition, modifications, documents and location affect an actual used asking price."],
      ["Can I use the newer model's service intervals?", "Do not assume they are the same. Use the manufacturer's manual or service guidance for the exact generation and local variant."],
      ["Will this seat height fit me?", `The published seat height is ${bike.seat} mm. Inseam, seat width, suspension sag, footwear, road camber and technique affect real reach. Sit on the exact unit before buying.`],
      ["Where is the current model?", `${current.brand} ${current.model} has its own local model page, with current-generation price references, a finance planner and comparison actions.`],
    ].map(([q, a]) => <details key={q}><summary>{q}<Icon name="plus" className="h-4 w-4" /></summary><p>{a}</p></details>)}</div></div></section>
    <div className="history-next-model"><div><p className="page-eyebrow">Continue with the current generation</p><h2>{current.brand} {current.model}</h2><p>Keep the generations separate. Take the next step without leaving MotoIndex.</p></div><a className="action-primary" href={bikePath(current)}>Explore {current.model}<Icon name="arrowRight" className="h-4 w-4" /></a></div>
    <SourceReferences sources={[{ label: "Generation record used for historical specifications", href: `https://motoindexph.com${bike.path}` }, { label: `${bike.brand} official service resources`, href: bike.serviceUrl }]} note="Historical launch references and source-record specifications are presented for research. No current used-market appraisal or stock guarantee is made." />
  </div></div>;
}

export function FamilyPage({ family }: { family: ModelFamily }) {
  const current = family.currentIds.map((id) => catalogById.get(id)).filter((bike): bike is CatalogBike => !!bike);
  const historical = archivedMotorcycles.filter((bike) => family.archiveIds.includes(bike.id));
  const rows = [...current.map((bike) => ({ name: bike.model, path: bikePath(bike), cc: bike.cc, seat: bike.seat, weight: bike.weight, price: bike.priceFrom, historical: false })), ...historical.map((bike) => ({ name: bike.name, path: bike.path, cc: bike.cc, seat: bike.seat, weight: bike.weight, price: bike.historicalPrice, historical: true }))];
  return <div className="inner-page family-page"><div className="page-container"><PageMeta title={`${family.brand} ${family.name} generations, prices and buying guide`} description={family.intro} /><PageIntro eyebrow="The model family" title={`${family.brand} ${family.name}. Which generation is yours?`} description={family.intro} breadcrumbs={[{ label: family.brand, href: `/motorcycles/${family.brand.toLowerCase()}` }, { label: family.name }]} action={<ShareButton />} />
    <section className="detail-section"><div className="section-line-heading"><div><p className="page-eyebrow">Current-model research</p><h2>Start with today's generation.</h2></div></div><div className="family-model-grid">{current.map((bike) => <BikeTile key={bike.id} bike={bike} />)}</div></section>
    <section className="detail-section"><div className="section-line-heading"><div><p className="page-eyebrow">The archive stays useful</p><h2>Earlier {family.name} generations.</h2></div></div><div className="family-model-grid">{historical.map((bike) => <a href={bike.path} className="archive-model-tile" key={bike.id}><div><HistoryImage bike={bike} /></div><section><p className="page-eyebrow">Previous generation</p><h3>{bike.name}</h3><p>{bike.generation}</p><strong>{money(bike.historicalPrice)}<small> historical launch SRP</small></strong><span>Read the full owner guide<Icon name="arrowRight" className="h-4 w-4" /></span></section></a>)}</div></section>
    <section className="detail-section"><div className="section-line-heading"><h2>The first-pass comparison.</h2></div><div className="brand-price-table-wrap"><table className="brand-price-table"><caption className="sr-only">{family.name} generation references</caption><thead><tr><th scope="col">Model</th><th scope="col">Price context</th><th scope="col">Engine</th><th scope="col">Seat height</th><th scope="col">Curb weight</th></tr></thead><tbody>{rows.map((row) => <tr key={row.path}><th scope="row"><a href={row.path}>{row.name}</a></th><td>{money(row.price)}<small>{row.historical ? "Historical launch reference" : "Published starting-price reference"}</small></td><td>{row.cc} cc</td><td>{row.seat} mm</td><td>{row.weight ? `${row.weight} kg` : "Not recorded"}</td></tr>)}</tbody></table></div></section>
    <section className="detail-section brand-editorial-columns"><div><p className="page-eyebrow">A better used-versus-new decision</p><h2>Condition matters more than a sticker gap.</h2></div><div className="brand-support-copy"><p>Current-model starting prices and historical launch SRPs are not equivalent offers. A used {family.name} needs an actual asking price, inspection and documentary check before the financial comparison means much.</p><p>Ask for the exact year and configuration, match engine and frame identifiers to the OR/CR, and budget for overdue consumables or service. Similar tire-size strings do not guarantee that all wheels, racks or components transfer across generations.</p><a href="/used-motorcycles/buying-checklist" className="text-link">Use the used-bike checklist<Icon name="arrowRight" className="h-4 w-4" /></a><a href="/ownership/cost-calculator" className="text-link">Estimate the full monthly cost<Icon name="arrowRight" className="h-4 w-4" /></a></div></section>
    <SourceNote>Current records and previous-generation launch prices are intentionally separated. Each generation opens its own local page with specifications, guidance and source citations.</SourceNote>
  </div></div>;
}