import { useState } from "react";
import type { CatalogBike } from "../catalog";
import { bikePath, money, publishedPrice, modelSources } from "../catalog";
import { PageIntro, PageMeta, ShareButton, SourceNote } from "../components/PageUI";
import SourceReferences from "../components/SourceReferences";
import { BikeImage } from "../components/BikeTile";
import { monthlyPayment } from "../tools";
import Icon from "../components/icons";

export const modelTopics: Record<string, { title: string; description: string; icon: string }> = {
  specs: { title: "Specifications", description: "The source-linked dimensions, engine and equipment details in one readable record.", icon: "doc" },
  price: { title: "Price & variants", description: "Published price references and the details to check in a current seller quote.", icon: "wallet" },
  installment: { title: "Installment planner", description: "Model your down payment, term and interest without losing sight of the total.", icon: "calculator" },
  "fuel-consumption": { title: "Fuel consumption & range", description: "Separate published economy from planning assumptions and calculate your own monthly fuel budget.", icon: "fuel" },
  "tire-size": { title: "Tire size & fitment", description: "Start with the recorded tire size, then verify load, speed and wheel compatibility.", icon: "gauge" },
  maintenance: { title: "Maintenance & service", description: "A practical ownership checklist with exact-model service guidance kept distinct from general advice.", icon: "wrench" },
  "top-speed": { title: "Top-speed evidence", description: "Manufacturer figures, independent tests and rider claims are not interchangeable evidence.", icon: "gauge" },
  "ownership-cost": { title: "Ownership cost", description: "Fuel, maintenance, insurance and registration, kept separate from the finance payment.", icon: "wallet" },
  "used-price": { title: "Used-bike price research", description: "Research the actual unit and total transaction rather than relying on generic depreciation.", icon: "tag" },
};

export default function ModelResearchPage({ bike, topic }: { bike: CatalogBike; topic: string }) {
  const definition = modelTopics[topic];
  const [price, setPrice] = useState(String(bike.priceFrom));
  const [down, setDown] = useState(20);
  const [term, setTerm] = useState(36);
  const [annualRate, setAnnualRate] = useState("12");
  const [distance, setDistance] = useState(900);
  const [economy, setEconomy] = useState(bike.economy ?? 40);
  const [fuelPrice, setFuelPrice] = useState(65);
  const [repairs, setRepairs] = useState("0");
  const [fees, setFees] = useState("0");
  const valid = [price, annualRate, repairs, fees].every((value) => value.trim() !== "" && Number.isFinite(Number(value)) && Number(value) >= 0) && Number(price) <= 10000000 && Number(annualRate) <= 100;
  const payment = valid ? monthlyPayment(Number(price) * (1 - down / 100), Number(annualRate), term) : 0;
  const pagePath = `${bikePath(bike)}/${topic}`;

  return <div className="inner-page research-page"><div className="page-container"><PageMeta title={`${bike.brand} ${bike.model} ${definition.title.toLowerCase()} Philippines`} description={definition.description} /><PageIntro eyebrow={`${bike.brand} ${bike.model} / Model research`} title={`${bike.model}: ${definition.title.toLowerCase()}.`} description={definition.description} breadcrumbs={[{ label: bike.brand, href: `/motorcycles/${bike.slug?.split("/")[0]}` }, { label: bike.model, href: bikePath(bike) }, { label: definition.title }]} action={<ShareButton />} />
    <div className="model-research-layout"><article className="model-research-body">
      {topic === "specs" && <><h2>One model. Consistent units.</h2><p>The specifications below belong to the recorded Philippine model. Source date: {bike.checked}. Check the dealer's exact variant and generation before treating a different unit as equivalent.</p><dl className="model-specifications">{[["Displacement", `${bike.cc} cc`], ["Power", `${bike.hp} hp`], ["Transmission", bike.transmission], ["Seat height", `${bike.seat} mm`], ["Curb weight", bike.weight ? `${bike.weight} kg` : "Not recorded"], ["Torque", bike.torque ? `${bike.torque} Nm` : "Not recorded"], ["Fuel tank", bike.tank ? `${bike.tank} L` : "Not recorded"], ["Front tire", bike.tires?.[0] || "Not recorded"], ["Rear tire", bike.tires?.[1] || "Not recorded"]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><h2>Brakes and equipment</h2><p>{bike.brakes || "An exact brake package is not attached to this record. Confirm the local trim and equipment; missing information is not evidence that ABS is or is not fitted."}</p><h2>Dimensions do not decide fit</h2><p>A {bike.seat} mm seat and the published weight are useful starting points. Seat width, suspension sag, footwear and rider technique affect actual reach. Test the controls and low-speed handling in person.</p><a className="text-link" href={`/fitment?bike=${bike.id}`}>Check your rider-fit context<Icon name="arrowRight" className="h-4 w-4" /></a></>}
      {(topic === "price" || topic === "installment") && <><h2>Keep the transaction in view.</h2><p>The source-linked price reference is {publishedPrice(bike)}, dated {bike.checked}. A higher trim, registration package, processing charge or promotion can change a current written quote.</p><div className="inline-research-planner"><label className="field-label">Purchase-price assumption<input type="number" className="field-input mt-2" min="0" max="10000000" value={price} onChange={(e) => setPrice(e.target.value)} /></label><label className="field-label">Down payment: {down}%<input type="range" min="0" max="100" step="5" className="ranger mt-5" value={down} onChange={(e) => setDown(Number(e.target.value))} /></label><label className="field-label">Term<select className="field-input mt-2" value={term} onChange={(e) => setTerm(Number(e.target.value))}>{[12, 24, 36, 48].map((months) => <option key={months} value={months}>{months} months</option>)}</select></label><label className="field-label">Nominal annual interest (%)<input type="number" className="field-input mt-2" min="0" max="100" value={annualRate} onChange={(e) => setAnnualRate(e.target.value)} /></label><div className="inline-research-result"><span>Monthly amortization estimate</span><strong aria-live="polite">{valid ? money(payment) : "Check inputs"}</strong>{valid && <small>Total before fees: {money(Number(price) * down / 100 + payment * term)}</small>}</div></div><p>Standard diminishing-balance calculation. Fees are excluded here. Compare a flat/add-on quotation in the full planner, rather than treating its rate as equivalent to this nominal annual rate.</p><a href={`/tools/motorcycle-loan-calculator?bike=${bike.id}&price=${valid ? Number(price) : bike.priceFrom}&down=${down}&months=${term}&rate=${valid ? Number(annualRate) : 12}`} className="action-primary">Include fees & compare interest methods<Icon name="arrowRight" className="h-4 w-4" /></a><h2>What to request from the dealer</h2><ul><li>The exact model, year, trim and color.</li><li>An itemized cash price including registration and other charges.</li><li>Down payment, amount financed, term, rate method and all fees.</li><li>The monthly payment, total payable and early-settlement terms.</li></ul></>}
      {(topic === "fuel-consumption" || topic === "ownership-cost") && <><h2>Start with the right economy basis.</h2><p>{bike.economy ? `The recorded ${bike.economy} km/L is ${bike.economyBasis === "published" ? "a published reference, not a guarantee for your route" : "a planning estimate, not a manufacturer-published claim"}.` : "No model-specific published economy figure is attached to this record. The initial 40 km/L below is an editable example for arithmetic only, not a claim about this motorcycle."} Traffic, load, speed, weather and condition affect real consumption.</p><div className="inline-research-planner"><label className="field-label">Distance per month: {distance} km<input className="ranger mt-4" type="range" min="0" max="4000" step="50" value={distance} onChange={(e) => setDistance(Number(e.target.value))} /></label><label className="field-label">Economy assumption: {economy} km/L<input className="ranger mt-4" type="range" min="10" max="100" step="0.1" value={economy} onChange={(e) => setEconomy(Number(e.target.value))} /></label><label className="field-label">Fuel price: {money(fuelPrice)} / L<input className="ranger mt-4" type="range" min="20" max="150" value={fuelPrice} onChange={(e) => setFuelPrice(Number(e.target.value))} /></label><div className="inline-research-result"><span>Estimated monthly fuel</span><strong aria-live="polite">{money(distance / economy * fuelPrice)}</strong><small>{(distance / economy).toFixed(1)} liters at your assumptions</small></div></div><h2>Fuel is only part of ownership.</h2><p>Set aside a realistic reserve for servicing and tires, and budget separately for insurance, registration, parking, gear, repairs and any loan. A fuel-only number is not the cost of owning the motorcycle.</p><a className="action-primary" href={`/ownership/cost-calculator?bike=${bike.id}&economy=${economy}&distance=${distance}&fuel=${fuelPrice}`}>Build the complete monthly budget<Icon name="arrowRight" className="h-4 w-4" /></a>{bike.tank && <p>The recorded {bike.tank} L tank gives {Math.round(bike.tank * economy)} km of theoretical full-tank arithmetic at your input. Allow a reserve; this is not guaranteed usable range.</p>}</>}
      {topic === "tire-size" && <><h2>Factory-size references.</h2><div className="tire-sizes"><div><span>Front</span><strong>{bike.tires?.[0] || "Not recorded"}</strong></div><div><span>Rear</span><strong>{bike.tires?.[1] || "Not recorded"}</strong></div></div><p>{bike.tires ? "These tire-size strings are attached to this model record. They are the start of a compatibility check, not a complete replacement approval." : "Do not borrow the tire size from a similar model. A complete tire record has not been established here; check the exact owner's manual and the current wheel installation."}</p><h2>Check more than the nominal size.</h2><ul><li>Correct load and speed ratings for the motorcycle.</li><li>Approved rim width, wheel application and construction.</li><li>Front/rear designation and rotation direction.</li><li>Correct tire pressures for the actual load and conditions.</li><li>Physical condition, age and any wheel modifications.</li></ul><p>Tire size does not establish pressure. Use the manufacturer's exact-model guidance. Have damaged rims, unusual wear or handling changes inspected by a qualified service provider.</p><a className="action-primary" href={`/tires?bike=${bike.id}`}>Open the tire reference tool<Icon name="arrowRight" className="h-4 w-4" /></a></>}
      {topic === "maintenance" && <><h2>Use the exact service schedule.</h2><p>A parsed, exact-model interval schedule is not attached to this record. Do not fill that gap with a generic oil, valve, coolant or belt interval. Identify the current owner's manual for the precise model year and market.</p><h2>Prepare for a useful service visit.</h2><ul><li>Bring the model year, current odometer and recent service receipts.</li><li>Describe symptoms and when they occur, rather than choosing parts by guesswork.</li><li>Ask which inspections and replacements the actual schedule requires.</li><li>Record the part numbers, fluid specifications and completed work.</li><li>Confirm any VIN-specific service campaign with the manufacturer.</li></ul><h2>{bike.transmission === "Automatic" ? "Pay attention to transmission service." : "Keep the drivetrain in the routine."}</h2><p>{bike.transmission === "Automatic" ? "Many automatic scooters use a belt-and-pulley CVT, but automatic transmission alone does not establish a specific layout. Check the exact model before ordering belts, rollers or final-drive fluids." : "Chain, sprocket, clutch and gearbox requirements are model-specific. Check condition and manufacturer guidance rather than applying one adjustment or replacement interval to every motorcycle."}</p><div className="article-next-steps"><div><a href={bike.transmission === "Automatic" ? "/maintenance/cvt-motorcycle" : "/maintenance/sprocket-motorcycle"}>Read the drivetrain guide<Icon name="arrowRight" className="h-4 w-4" /></a><a href="/maintenance/change-oil-motorcycle">Oil-change guidance<Icon name="arrowRight" className="h-4 w-4" /></a><a href="/ownership/safety-campaigns">Service-campaign checks<Icon name="arrowRight" className="h-4 w-4" /></a></div></div></>}
      {topic === "top-speed" && <><h2>No verified numeric top-speed claim in this record.</h2><p>The record contains {bike.cc} cc displacement and {bike.hp} hp output. Neither figure is enough to establish a maximum speed. A claim from a different generation, a tuned engine or a speedometer-only video is not a verified result for this exact motorcycle.</p><h2>What would make a test useful?</h2><ul><li>Correct model, generation, local variant and stock configuration.</li><li>A repeatable measurement method, preferably independent of dashboard error.</li><li>Disclosed rider load, wind, gradient and test conditions.</li><li>A controlled, lawful test environment and an identifiable source.</li></ul><p>Until suitable evidence is recorded, publishing a guessed number would be misleading. Do not attempt a maximum-speed test on a public road.</p><a className="action-secondary" href="/methodology">Read the evidence methodology<Icon name="arrowRight" className="h-4 w-4" /></a></>}
      {topic === "used-price" && <><h2>A used price needs an actual unit.</h2><p>Published new-price context is {publishedPrice(bike)}. It is not a used-bike valuation. Age, mileage, condition, registration, service history, modifications and location can materially change a seller's asking price.</p><h2>Budget from the quote you have.</h2><div className="inline-research-planner">{[["Actual seller offer", price, setPrice], ["Inspection-based repair reserve", repairs, setRepairs], ["Transfer and transaction budget", fees, setFees]].map(([label, value, setter]) => <label className="field-label" key={String(label)}>{String(label)}<input type="number" className="field-input mt-2" min="0" value={String(value)} onChange={(e) => (setter as (value: string) => void)(e.target.value)} /></label>)}<div className="inline-research-result"><span>Initial purchase budget</span><strong>{valid ? money(Number(price) + Number(repairs) + Number(fees)) : "Check inputs"}</strong><small>Not an appraisal. Running costs and finance excluded.</small></div></div><p>The price input initially uses the new-price reference as a placeholder; replace it with an actual offer. Do not treat the starting number as an observed used listing.</p><a className="action-primary" href="/used-motorcycles/buying-checklist">Open the complete used-bike checklist<Icon name="arrowRight" className="h-4 w-4" /></a></>}
      <SourceReferences sources={modelSources(bike)} note={`This local ${definition.title.toLowerCase()} page uses the recorded model data and explicitly stated planning assumptions. Missing information is not represented as a verified specification.`} />
    </article><aside className="model-research-aside"><a className="research-bike-link" href={bikePath(bike)}><BikeImage bike={bike} /><span>{bike.brand}</span><strong>{bike.model}</strong><small>Back to model overview<Icon name="arrowRight" className="h-3.5 w-3.5" /></small></a><nav aria-label="Related model research">{Object.entries(modelTopics).map(([key, item]) => <a href={`${bikePath(bike)}/${key}`} key={key} aria-current={key === topic ? "page" : undefined}><Icon name={item.icon} className="h-4 w-4" />{item.title}</a>)}</nav><SourceNote>Record date: {bike.checked}. Confirm the exact local variant before purchase.</SourceNote></aside></div>
    <a href={bikePath(bike)} className="text-link mt-8">Back to all {bike.model} details<Icon name="arrowRight" className="h-4 w-4" /></a><span className="sr-only">Page: {pagePath}</span>
  </div></div>;
}