import type { ArticleBody } from "./content";

const honda = { label: "Honda Philippines maintenance planner", href: "https://www.hondaph.com/service-calculator" };
const yamaha = { label: "Yamaha Philippines After Sales", href: "https://aftersales.yamaha-motor.com.ph/" };
const suzuki = { label: "Suzuki Philippines After Sales", href: "https://mc.suzuki.com.ph/after-sales/" };
const lto = { label: "Land Transportation Office: current issuances and transaction guidance", href: "https://lto.gov.ph/" };
const bps = { label: "DTI-BPS: PS and ICC marks", href: "https://bps.dti.gov.ph/product-certification/ps-and-icc-marks" };
const insurance = { label: "Insurance Commission Philippines", href: "https://www.insurance.gov.ph/" };

export const fullEditorial: Record<string, ArticleBody> = {
  "/maintenance/parts-of-motorcycle": {
    sourced: true, checked: "2026-08-26", takeaways: ["Learn the system before choosing a replacement part.", "A scooter CVT and a chain-driven motorcycle need different service procedures.", "Dimensions, fluids and intervals must match the exact model."],
    sections: [
      { title: "Controls and the rider interface", text: ["The handlebar area normally brings together the throttle, front-brake control, switches, mirrors and instruments. A manual motorcycle may also have a clutch lever. Learn the exact control layout from the owner's manual before riding an unfamiliar machine.", "Check that controls move freely, return correctly where applicable and are not obstructed by added accessories. A phone mount or loose rainwear must not interfere with the steering or levers."], checks: ["Locate the throttle, brakes, switches and horn.", "Adjust mirrors before setting off.", "Identify the clutch and gear controls where fitted.", "Confirm full, unobstructed steering movement."] },
      { title: "Engine, intake, exhaust and cooling", text: ["The engine converts fuel into motion. Its supporting systems can include an air cleaner, fuel injection or carburetion, an exhaust and the engine-oil circuit. A liquid-cooled motorcycle also has a radiator and coolant circuit; an air-cooled model does not have the same coolant service requirement.", "Fluids, capacities, filters and replacement parts are not universal. An oil grade or filter that suits another model from the same brand may still be wrong for yours."] },
      { title: "Drivetrain: chain, sprockets or CVT", text: ["Manual and many underbone motorcycles transfer power through a chain and sprockets. Automatic scooters commonly use a continuously variable transmission with a V-belt and pulleys. Those layouts need different inspection and replacement procedures.", "Follow the exact model's guidance for chain slack, lubrication, belt inspection and replacement. A generic interval from another motorcycle is not a safe substitute for the manual."] },
      { title: "Chassis, suspension, wheels and brakes", text: ["The frame, fork, rear suspension, wheels, tires and brakes work together to support the load, change direction and stop. Published tire sizes are only part of fitment: pressure, load rating, speed rating and front/rear application matter too.", "Have damage, unusual play, fluid leaks or abnormal brake feel checked by a qualified technician. Do not infer torque values or service limits from appearance."] },
      { title: "Electrical and periodic service items", text: ["The battery, charging system, lights, fuses, spark plug and sensors support starting and electrical functions. Manufacturers include many of these in periodic inspection and replacement schedules.", "When ordering a part, identify the motorcycle's model, year and variant first. Keep the part specification, service date, odometer reading and receipt in your maintenance record."] },
    ], faqs: [{ q: "Are parts interchangeable within a motorcycle brand?", a: "Not automatically. Mounting points, dimensions, electrical ratings and fluid specifications can differ between models, years and variants." }, { q: "Where do I find the correct replacement part?", a: "Use the exact owner's manual, manufacturer parts catalog or a qualified authorized parts source. A marketplace title is not proof of fitment." }], sources: [honda, yamaha, suzuki],
  },
  "/maintenance/coolant-for-motorcycle": {
    sourced: true, checked: "2026-08-26", takeaways: ["First establish whether the engine is liquid-cooled.", "Coolant color does not establish compatibility.", "Never open a hot, pressurized cooling system."],
    sections: [
      { title: "Confirm the cooling system", text: ["Not every motorcycle uses radiator coolant. Air-cooled models and liquid-cooled models have different service requirements. Identify the exact system in the owner's manual before buying a fluid or following a service guide.", "For a liquid-cooled bike, learn which reservoir and cap are involved in the manufacturer's inspection procedure. Do not assume the layout matches a previous motorcycle you owned."] },
      { title: "Choose by specification, not color", text: ["Coolant chemistry, concentration and mixing instructions can vary. The required specification belongs to the exact motorcycle and model year, not simply to a product labeled 'motorcycle coolant'.", "If the fluid already in the system is unknown, do not mix another product on the basis of color. Follow the manufacturer's service procedure or have the system assessed by a qualified technician."], checks: ["Exact model and cooling system identified.", "Required coolant specification confirmed.", "Mixing and concentration instructions checked.", "Existing fluid type known, or professional service arranged."] },
      { title: "Let the motorcycle cool", text: ["A hot cooling system can be pressurized. Opening a radiator cap or pressurized reservoir can release hot fluid and cause injury. Let the motorcycle cool and follow the model's inspection instructions.", "Unexpected coolant loss, repeated overheating or visible leaks require diagnosis. Topping up repeatedly is not a repair for an underlying fault."] },
      { title: "Use the model's replacement interval", text: ["Manufacturers may specify elapsed-time or mileage-based intervals. There is no universal replacement distance for every motorcycle.", "Record the fluid specification, quantity, date and odometer reading after service. That record is more useful than assuming a color or brand tells you what is in the system."] },
    ], faqs: [{ q: "Can I use car coolant in a motorcycle?", a: "Only if it meets the exact requirements in the motorcycle manufacturer's guidance. Do not assume compatibility from the general product category." }, { q: "Can I mix coolant types?", a: "Do not mix unknown or incompatible coolant types. Check the chemistry and manufacturer's mixing instructions; when uncertain, follow the specified service procedure." }], sources: [honda, yamaha, suzuki],
  },
  "/maintenance/sprocket-motorcycle": {
    sourced: true, checked: "2026-08-26", takeaways: ["The chain and sprockets wear as a system.", "Tooth counts change the final-drive ratio.", "Pitch, mounting pattern and alignment must all match."],
    sections: [
      { title: "The chain and sprockets work together", text: ["On a chain-driven motorcycle, the front and rear sprockets transfer engine power through the drive chain. Wear in one component can accelerate wear in its mating parts.", "Inspect the system as a whole rather than deciding from the appearance of a single sprocket. A new chain against badly worn teeth can have a short service life."] },
      { title: "Inspect condition, slack and lubrication", text: ["Use the exact owner's manual for chain slack, measurement conditions, adjustment points and inspection guidance. Damaged teeth, stiff links, excessive wear or repeated adjustment deserve a closer service inspection.", "Do not use a universal tension setting. Suspension position, motorcycle layout and the manufacturer's measuring procedure affect what the correct adjustment means."], checks: ["Correct chain-slack procedure located in the manual.", "Chain links and sprocket teeth inspected.", "Lubrication and adjustment history reviewed.", "Abnormal wear assessed by a qualified technician."] },
      { title: "Changing tooth counts changes gearing", text: ["A larger rear sprocket generally shortens final-drive gearing rather than automatically increasing maximum speed. It can raise engine rpm at a given road speed and change acceleration characteristics.", "A gearing change can also affect speedometer behavior on some motorcycles. Use stock sizing as the starting point unless a qualified source supports a specific change for the exact bike."] },
      { title: "Order model-correct replacement parts", text: ["Pitch, tooth count, mounting pattern, alignment and chain specification must be compatible. Diameter or visual similarity alone cannot confirm fitment.", "Use the manufacturer parts catalog or a reliable model-specific supplier. Installation, alignment and fastening requirements should be followed by someone with the proper tools and training."] },
    ], faqs: [{ q: "Must I replace the chain and both sprockets together?", a: "They wear together, but the decision depends on their measured condition and manufacturer guidance. Do not fit a new part against badly worn mating components without an inspection." }, { q: "Does a bigger rear sprocket make a bike faster?", a: "It usually shortens the gearing, which is not the same as increasing top speed. Evaluate rpm, gearing and compatibility for the exact motorcycle." }], sources: [yamaha, suzuki],
  },
  "/maintenance/cvt-motorcycle": {
    sourced: true, checked: "2026-08-26", takeaways: ["A scooter CVT varies its ratio through pulleys and a belt.", "The V-belt is a scheduled wear item.", "Belt, rollers, clutch and pulleys need system-level inspection."],
    sections: [
      { title: "How a scooter CVT works", text: ["A continuously variable transmission changes the effective drive ratio through pulleys and a V-belt instead of manual gear selection. The exact layout, service parts and specifications vary by model.", "That makes an automatic scooter convenient in stop-go use, but does not remove maintenance. The belt, rollers, clutch and related components need the checks specified by the manufacturer."] },
      { title: "The belt has a service schedule", text: ["Manufacturers publish inspection and replacement requirements for the V-belt and related parts. Use the schedule for the exact motorcycle, generation and local variant rather than a generic mileage figure.", "An invoice stating that a CVT was 'cleaned' does not necessarily show that wear was measured or that a belt was replaced. Ask for the exact work and parts listed in the service record."], checks: ["Exact model-year service schedule identified.", "Belt inspection or replacement record checked.", "Replacement belt specification confirmed.", "Service work and odometer reading recorded."] },
      { title: "Diagnose noise or vibration as a system", text: ["Acceleration changes, unusual noise or vibration can have several causes. A qualified inspection can distinguish belt wear from roller, clutch, bearing or engine problems.", "Replacing one part by guesswork can leave the actual problem unresolved. Avoid assuming that the most popular modification is the correct fix for a symptom."] },
      { title: "Fitment and roller weights are model-specific", text: ["Belts and rollers may look similar while differing in dimensions, weight and material. Match the part number or manufacturer-approved specification.", "Changing roller weight alters transmission behavior and engine rpm. A tuning choice is not a universal improvement; use stock specification unless a qualified source supports the change and its trade-offs."] },
    ], faqs: [{ q: "When should a scooter V-belt be replaced?", a: "Follow the exact model's inspection and replacement schedule. There is no universal belt replacement interval." }, { q: "Can roller weights change acceleration?", a: "Yes. They change how the CVT operates and the engine rpm it uses. That does not automatically improve economy, reliability or suitability for your riding." }], sources: [yamaha, honda],
  },
  "/maintenance/motorcycle-oil": {
    sourced: true, checked: "2026-08-26", takeaways: ["Match viscosity, performance standard and capacity.", "Wet-clutch motorcycles and scooters can need different oil specifications.", "A higher price does not make an incompatible oil correct."],
    sections: [
      { title: "Begin with the owner's manual", text: ["The specified viscosity range, performance standard and oil quantity can vary with the engine and market. Match those requirements before comparing brands or prices.", "Check the manual for the actual motorcycle and model year. A similar engine size or another bike from the same manufacturer is not enough to establish the correct oil."] },
      { title: "Understand what the oil is lubricating", text: ["Some motorcycles share engine oil with a wet clutch, while many scooters use engine oil separately from their final drive. These systems can require different fluid specifications.", "Do not assume that scooter engine oil and final-drive oil are the same. Check the instructions for each fluid, including the quantity and replacement procedure."] },
      { title: "Choose evidence over price or marketing", text: ["A premium oil that does not meet the required specification is not a better choice. Correct specification, service interval and a trustworthy product source come first.", "Manufacturer parts and after-sales resources can help verify genuine product lines. Be cautious about listings without clear specifications, seller identity or packaging provenance."], checks: ["Required viscosity and performance standards checked.", "Wet-clutch or final-drive requirements understood.", "Product specification and seller checked.", "Oil quantity and level-check procedure confirmed."] },
      { title: "Keep a record and dispose of used oil properly", text: ["Record the oil specification, service date, odometer and receipt. Use the manufacturer's level-check method and have leaks or unusual consumption investigated.", "Used oil needs appropriate collection and disposal. If you do not have the tools or training for the procedure, have a qualified service provider carry it out."] },
    ], faqs: [{ q: "Is 10W-40 right for every motorcycle?", a: "No. It is a common viscosity but not a universal requirement. Confirm both viscosity and performance standard for the exact model." }, { q: "What is the best motorcycle oil?", a: "The correct specification from the owner's manual is the starting point. Brand preference and price come after compatibility and service requirements." }], sources: [yamaha, suzuki, honda],
  },
  "/guides/motorcycle-helmet-certification-philippines": {
    sourced: true, checked: "2026-09-09", takeaways: ["Local conformity and overseas certification are separate checks.", "Inspect the exact helmet, not only a listing photograph.", "Certification is model- and unit-specific, not brand-wide."],
    sections: [
      { title: "What to look for in the Philippines", text: ["DTI-BPS places motorcycle helmets and visors under mandatory product certification. Its guidance says covered products distributed in the Philippine market must bear the applicable Philippine Standard mark or Import Commodity Clearance sticker.", "Inspect the exact product being sold. A marketplace badge, seller claim or image of another unit is not the same as checking the applicable marking and label yourself."], checks: ["Exact brand, model and local unit identified.", "Applicable PS or ICC marking inspected.", "Certification label compared with the seller's claim.", "Questionable markings checked with DTI-BPS resources."] },
      { title: "PS and ICC are different conformity routes", text: ["The PS mark relates to the Philippine Standard certification mark licensing scheme. ICC refers to the Import Commodity Clearance scheme for imported products.", "Keep model, batch and seller information if a product needs verification. Use current BPS guidance rather than relying on an old image of what a sticker should look like."] },
      { title: "Where ECE fits", text: ["ECE is a separate international helmet homologation system. MotoIndex records a model's explicit ECE claim when a source supports it; an ECE label is not used as a replacement for checking local Philippine conformity.", "The reviewed BPS product-coverage page references PNS/UN ECE 22:2007 in its framework. Model certifications and local compliance can differ by market or batch, so verify both rather than treating one label as proof of everything."] },
      { title: "Never certify a whole brand by association", text: ["A brand can sell several helmet families, shell constructions and market versions. A certification on one model does not automatically apply to every product with the same logo.", "That is also why a filter for ECE 22.06 needs explicit model-level evidence. Missing certification data should remain a question to verify, not a silently assumed badge."] },
      { title: "Fit remains essential", text: ["A compliant helmet still needs the right size and head shape, secure retention and an appropriate condition. Certification cannot compensate for a loose fit or prior impact damage.", "Try the model on when possible and follow the manufacturer's fit and replacement guidance. Inspect the helmet that will actually be delivered, including its labels and accessories."] },
    ], faqs: [{ q: "Is an ECE label alone enough for a Philippine purchase?", a: "Do not rely on it alone. Verify the applicable PS or ICC conformity marking and the exact helmet's certification label." }, { q: "Can I verify an ICC sticker?", a: "DTI-BPS provides verification resources. Follow the current BPS instructions and retain the product and batch details when making an inquiry." }], sources: [bps, { label: "DTI-BPS helmet and visor product coverage", href: "https://bps.dti.gov.ph/component/content/article?Itemid=111&id=101" }, { label: "DTI-BPS product certification", href: "https://bps.dti.gov.ph/product-certification" }],
  },
  "/ownership/transfer-of-ownership": {
    sourced: true, checked: "2026-08-26", takeaways: ["A deed of sale is one requirement, not the entire transfer.", "Verify identifiers, seller authority and registration records before payment.", "Online eligibility and required originals must be checked with LTO."],
    sections: [
      { title: "Prepare the general transfer requirements", text: ["The reviewed 2025 LTO motorcycle ownership rules list a duly notarized deed of conveyance or agreement, such as a deed of sale, the OR/CR, valid HPG clearance and a valid government-issued ID among the general requirements.", "Corporate ownership and other transaction types can require additional documents, including a secretary certificate where applicable. Check the current Citizen's Charter and the checklist for the actual case before filing."], checks: ["Seller identity and authority verified.", "Notarized conveyance document prepared.", "OR/CR and motorcycle identifiers matched.", "Applicable HPG clearance and valid identification prepared.", "Additional transaction-specific requirements confirmed."] },
      { title: "If registration is not current", text: ["The reviewed rules allow a transfer to be processed even when the motorcycle is not registered for the current year, but state that the Certificate of Registration is not released until registration is renewed.", "That distinction does not make expired registration irrelevant. Confirm the required renewal steps, assessed charges and release conditions with the office processing your transaction."] },
      { title: "Check the actual submission process", text: ["The 2025 rules contemplate in-person and online submission. Scanned requirements may be accepted online subject to producing originals when required, and an affidavit of authenticity is specified for online submissions.", "Do not assume that a rule allowing online filing means your particular transaction is ready for a fully online process. Verify the current operational requirements and official payment channel."] },
      { title: "For repossessed or dealer-resold units", text: ["The reviewed rules require the dealer to report repossession. A later sale or disposition must follow the reporting and registration requirements for the new owner.", "Ask the seller to explain the documentary chain and transfer path in writing. An attractive repo price does not resolve missing ownership records, liens or mismatched identifiers."] },
    ], faqs: [{ q: "Is a notarized deed enough to complete a transfer?", a: "No. It is part of the required set, alongside registration records, clearances, identification and any additional transaction-specific requirements." }, { q: "Can an unregistered-for-the-year motorcycle be transferred?", a: "The reviewed 2025 rules allow processing but withhold the CR until registration is renewed. Confirm the current instructions for your case with LTO." }], sources: [lto],
  },
  "/ownership/deed-of-sale-motorcycle-philippines": {
    sourced: true, checked: "2026-08-26", takeaways: ["Complete the parties' and motorcycle's information before signing.", "Notarization does not replace the LTO transfer process.", "Resolve unclear ownership or identifiers before buying."],
    sections: [
      { title: "What the conveyance document is for", text: ["The reviewed 2025 motorcycle ownership rules require a duly notarized deed of conveyance or agreement, including a deed of sale or donation, among the general transfer requirements. The rule looks at the substance of the agreement rather than just its title.", "For a purchase, the document should accurately reflect the transaction and parties. Obtain qualified legal advice if the ownership, authority to sell or transaction terms are unusual or disputed."] },
      { title: "Match the parties and the physical unit", text: ["Before signing or paying, check the parties' information against valid identification and the seller's authority to transfer the motorcycle. Match the model, frame or chassis and engine identifiers to the physical unit and OR/CR.", "Mismatches should be resolved before proceeding, not explained away as a detail to fix later. Keep completed copies and transaction records."], checks: ["Seller and buyer identities confirmed.", "Seller's authority to transfer established.", "Engine and chassis identifiers matched to the documents.", "Terms and motorcycle description complete.", "Notarization and formal transfer steps arranged."] },
      { title: "A deed is not the whole transfer", text: ["The document does not replace the OR/CR, required HPG clearance, identification or other LTO requirements. Complete the formal ownership-transfer transaction through the applicable process.", "Ask what the seller will provide, when documents will be released and what charges are included. Keep the transfer requirements separate from a dealer's financing or release promises."] },
      { title: "Do not leave an open deed as the end state", text: ["Blanks, incomplete identities or indefinite delays in transfer can create liability, identity and processing problems. The safer goal is a completed, notarized transaction document followed by formal LTO transfer.", "This guide is not a legal document template and cannot validate a disputed sale. Have a qualified professional review unusual circumstances before you commit money."] },
    ], faqs: [{ q: "Does a motorcycle deed of sale need notarization?", a: "The reviewed LTO transfer requirements call for a duly notarized deed or conveyance agreement. Confirm the current requirements for the transaction." }, { q: "Should I rely on an open deed?", a: "An incomplete document can create identity and transfer problems. Aim for completed documents and a formal transfer, with qualified advice when necessary." }], sources: [lto],
  },
  "/ownership/motorcycle-insurance": {
    sourced: true, checked: "2026-08-25", takeaways: ["CTPL and own-damage cover are not the same thing.", "Read exclusions, deductibles, dates and insured value.", "Use an Insurance Commission-regulated insurer and a current quote."],
    sections: [
      { title: "CTPL is the compulsory registration cover", text: ["Insurance Commission guidance identifies compulsory third-party liability as the mandatory motor-vehicle insurance used for registration or renewal. Arrange the required cover and verify that its period fits the registration transaction.", "A dealer estimate or an online product listing is not proof that a policy is active. Check the insurer, policy details and effective dates."] },
      { title: "Understand what CTPL does not cover", text: ["CTPL focuses on liability for third-party death or bodily injury under the policy and applicable rules. It is not automatically insurance for damage to your own motorcycle or for theft.", "A comprehensive policy can add own-damage, theft and optional protections, depending on its terms. The word 'comprehensive' does not mean that every event is covered without an exclusion or deductible."] },
      { title: "Review the current liability limit and schedule", text: ["Insurance Memorandum Circular 2024-01 increased compulsory motor-vehicle third-party liability limits to PHP 200,000 across motor-vehicle types, as noted in the reviewed source. Verify the current policy schedule and Commission guidance when buying.", "Compare proposals using the same insured value, risks, term and deductible. A cheaper premium can reflect different coverage rather than a better equivalent offer."], checks: ["Insurer checked against current regulatory information.", "Coverage dates and motorcycle identifiers verified.", "Insured value, limits and deductibles understood.", "Theft, own-damage and optional risks checked separately.", "Claim procedure and required documents reviewed."] },
      { title: "Build a budget from a real quote", text: ["The linked planner lets you enter a premium rate, fees and CTPL quote. A percentage is a planning assumption until an insurer provides the actual terms.", "Avoid double-counting CTPL if it is already included in a package. Keep insurance and registration charges separate when comparing dealer quotations."] },
    ], faqs: [{ q: "Does CTPL pay for damage to my own motorcycle?", a: "CTPL is focused on third-party death or bodily-injury liability. Check comprehensive policy terms for own-damage and theft coverage." }, { q: "Is the lowest insurance premium always the best?", a: "No. Compare insured value, exclusions, deductibles, claims support and policy period before treating two quotations as equivalent." }], sources: [insurance, lto],
  },
  "/ownership/safety-campaigns": {
    sourced: true, checked: "2026-08-25", takeaways: ["Campaign eligibility can depend on the VIN or frame number.", "An empty notice list does not mean no campaign applies.", "Confirm the remedy and appointment with the manufacturer or authorized service center."],
    sections: [
      { title: "Check the exact motorcycle", text: ["Recall, service-campaign and product-update eligibility can be vehicle-specific. Identify the correct model, year and manufacturer, then use the official checker or service contact.", "Do not publish your full frame or engine identifier on a public forum. Use the manufacturer's intended private checking process or provide it directly to an authorized service center."], checks: ["Model and year verified from the records.", "Frame or engine identifier available for the official check.", "Manufacturer campaign checker or service contact identified.", "Any required inspection or remedy confirmed in writing."] },
      { title: "Honda and Suzuki vehicle checks", text: ["Honda Philippines offers a Product Update page using engine or frame information. Suzuki Philippines provides an official service-campaign form for motorcycle chassis or frame checks.", "A local research page cannot determine eligibility from the model name alone. Follow the official result and contact the manufacturer if the identification or outcome is unclear."] },
      { title: "Yamaha and Kawasaki support", text: ["Use Yamaha Philippines' after-sales and service-campaign resources or an authorized Yamaha service center for a VIN-specific confirmation.", "For Kawasaki, contact the Philippine customer or service network with the exact motorcycle information. A general notice list is not a substitute for a vehicle-level check."] },
      { title: "Keep the completion record", text: ["Ask what work is required, whether there are operating instructions before service and how the completed remedy is recorded. Keep the service paperwork with the motorcycle's history.", "This directory does not certify that a motorcycle is unaffected. If you notice a potential safety defect or receive a notice, seek manufacturer guidance promptly."] },
    ], sources: [{ label: "Honda Philippines Product Update", href: "https://www.hondaph.com/product-update" }, { label: "Suzuki Philippines Service Campaign", href: "https://mc.suzuki.com.ph/service-campaign/" }, yamaha, { label: "Kawasaki Philippines customer support", href: "https://kawasakileisurebikes.ph/contact-us/" }],
  },
  "/guides/electric-scooters-philippines": {
    sourced: true, checked: "2026-08-27", takeaways: ["Compare the battery arrangement, not only the advertised vehicle price.", "Claimed range depends on the battery configuration and test conditions.", "Road-going L3 electric motorcycles still need registration."],
    sections: [
      { title: "The locally documented starting lineup", text: ["The source set covers VinFast Evo, Feliz II and Viper electric scooters introduced in the Philippines. The published starting references are PHP 62,900, PHP 64,900 and PHP 73,900 respectively.", "Those lowest advertised prices use battery subscription. They are not the same transaction as buying the motorcycle with one or two batteries owned outright. The local electric-model pages keep this distinction visible."] },
      { title: "Battery subscription or battery ownership?", text: ["Buying batteries changes the upfront amount and ownership arrangement. Compare the subscription fee, included battery configuration, swapping access, charging arrangements and written warranty before choosing.", "Add the relevant subscription charge to your monthly plan. A charging-cost calculation alone does not represent the full running cost if a recurring battery fee applies."], checks: ["Vehicle price and battery arrangement listed separately.", "Subscription fee or battery purchase quote in writing.", "Charging and swapping access confirmed for the intended route.", "Vehicle and battery warranty terms reviewed."] },
      { title: "Read the claimed-range conditions", text: ["The Evo source lists 85 km with one battery and 150 km with two. Feliz II and Viper list 82 km and 145 km respectively. These are published claims, not a guarantee for every rider or route.", "Speed, hills, payload, weather and battery condition can change consumption. Keep a reserve and use a measured real-world energy-use figure when one becomes available to you."] },
      { title: "Confirm registration and everyday support", text: ["The source records these models as L3 motorcycles without sidecars. Match the exact model and battery configuration to the sales and registration documents.", "Check servicing, replacement parts, battery replacement terms and safe charging before focusing on a low monthly energy bill. An electric drivetrain does not remove tire, brake or suspension maintenance."] },
    ], faqs: [{ q: "Does the starting price include battery ownership?", a: "The lowest advertised references in this set use battery subscription. Obtain a separate written quote for one- or two-battery ownership." }, { q: "Can I treat the claimed range as my commute range?", a: "No. Compare the test conditions and configuration, allow a reserve and account for your speed, payload, route and battery condition." }], sources: [{ label: "VinFast Philippines", href: "https://vinfastauto.ph/" }, lto],
  },
  "/guides/e-bike-vs-motorcycle": {
    sourced: true, checked: "2026-08-27", takeaways: ["The seller's word 'e-bike' does not determine the legal category.", "L3 electric motorcycles are road-going motorcycles.", "Classification affects registration, licensing and operating rules."],
    sections: [
      { title: "The motor is not the only distinction", text: ["LTO classification considers the vehicle design and performance, not just whether it runs on electricity. Lower-speed light electric vehicles and L3 electric motorcycles can have different registration, licensing and operating requirements.", "A product name in an online listing is not the official classification. Before payment, ask for the documents covering the exact unit and configuration."] },
      { title: "What the L3 category means", text: ["The referenced LTO Administrative Order describes L3 electric motorcycles as two-wheeled vehicles powered solely by electricity and capable of more than 50 km/h. They are registered as motorcycles and require the applicable motorcycle driving authorization.", "VinFast Evo, Feliz II and Viper are examples in the source dataset. Their one- and two-battery versions should be matched to the actual model-classification documents."] },
      { title: "Check lower-speed classifications separately", text: ["Registration and driver requirements for other electric vehicle categories depend on the exact class and current operating rules. Do not transfer an exemption or restriction from one category to another.", "Also check where the vehicle may legally be operated. Permission to own a vehicle does not by itself establish permission for every road on your route."], checks: ["Exact LTO category requested from the seller.", "Model-classification and registration documents reviewed.", "Required driving authorization confirmed.", "Road-use restrictions checked for the planned commute."] },
      { title: "Compare the whole ownership arrangement", text: ["Alongside classification, compare battery ownership, charging access, service support and the full price. A vehicle sold under the broad label 'e-bike' may still carry motorcycle registration and ongoing ownership costs."] },
    ], faqs: [{ q: "Is every electric two-wheeler registration-free?", a: "No. Registration depends on its LTO category and current rules. L3 electric motorcycles must be registered." }, { q: "Should I ask for LTO classification documents?", a: "Yes. Confirm the exact model and category instead of treating a marketplace label as proof." }], sources: [{ label: "LTO Administrative Order 2021-039", href: "https://lto.gov.ph/wp-content/uploads/2023/09/AO_2021-039.pdf" }, lto],
  },
  "/guides/electric-motorcycle-registration-philippines": {
    sourced: true, checked: "2026-08-27", takeaways: ["Electric does not mean automatically registration-free.", "Match model and battery configuration to the documents.", "Get all dealer registration charges and services in writing."],
    sections: [
      { title: "Start with the exact LTO category", text: ["Electric motorcycles used on public roads are not automatically exempt from registration. The exact LTO classification determines the registration and driver requirements.", "The reviewed source lists model-classification circulars for the VinFast Evo, Feliz II and Viper in one- and two-battery configurations. They are L3 motorcycles without sidecars and are accepted for motorcycle registration."] },
      { title: "Ask for the documents before paying", text: ["The sales invoice, model-classification evidence and registration paperwork should describe the exact vehicle and battery configuration. Do not accept a broad 'e-bike' description as enough detail."], checks: ["Written invoice names the exact model and battery configuration.", "Certificate of stock reported and classification evidence requested.", "Registration service, MVUC and processing charges itemized.", "Battery subscription or ownership agreement reviewed.", "Vehicle and battery warranty terms supplied in writing."] },
      { title: "Clarify what the dealer will process", text: ["Ask whether registration processing is included, what documents you will receive, the expected timeline and all fees. Keep the quote and receipts.", "Do not assume that EV incentives under EVIDA remove registration requirements for an L3 motorcycle. Confirm the actual rule and transaction applicable to the unit."] },
      { title: "Keep ownership and compliance connected", text: ["Record battery ownership or subscription terms alongside the vehicle documents. When selling or buying used, make sure the battery arrangement can be transferred or continued as required.", "Use current LTO guidance when transacting. A source-dated guide is a planning reference, not an official registration assessment or approval."] },
    ], faqs: [{ q: "Do the VinFast models in this index need registration?", a: "Yes. The reviewed source classifies Evo, Feliz II and Viper as L3 motorcycles without sidecars for public-road use." }, { q: "Does EVIDA make L3 motorcycles registration-free?", a: "No. Incentives do not automatically remove registration and applicable motorcycle-license requirements." }], sources: [lto, { label: "VinFast Philippines", href: "https://vinfastauto.ph/" }],
  },
  "/about": {
    sourced: true, sections: [
      { title: "One place for the facts behind your ride", text: ["MotoIndex PH brings together information that is often scattered across manufacturer pages, dealer listings, owner manuals and product catalogs. The focus is Philippine motorcycle prices, specifications and ownership research.", "The useful question is not simply which motorcycle has the biggest engine. It is which model, generation, fit and ownership arrangement suits the rider's real use."] },
      { title: "Motorcycles, gear and ownership", text: ["Motorcycle research includes prices, core specifications, trims, tire sizes, comparisons and model history. Helmet, tire and accessory pages keep exact size or mounting evidence separate from general guidance.", "The connected tools let you save a shortlist, compare the same units, check published seat-height context and model a budget with your own assumptions. No account is needed for the browser-local garage."] },
      { title: "Editorial responsibility", text: ["Erwin Valles is the named author and editor behind MotoIndex Philippines buyer and research content. The source site's work is built around traceable manufacturer, government and Philippine market references.", "This redesigned interface presents source-backed model data and editorial content in connected pages. It is not an official manufacturer website, dealer inventory feed or lending service."] },
      { title: "Dates and uncertainty stay visible", text: ["Changing facts, including prices, need a source and a checked date. Published references are not promises of a today's seller quote or proof of stock.", "Missing data is not filled with an invented specification. Planning estimates remain separate from manufacturer-published facts, and previous-generation prices remain historical."] },
    ],
  },
  "/methodology": {
    sourced: true, sections: [
      { title: "Identify the exact model", text: ["Generations, trims, helmet models and accessories are kept separate. An older version should never inherit the price or equipment of a newer model simply because the family name is familiar.", "Match the brand, model, generation, local market and variant before comparing specifications. Where one figure covers a model family, the uncertainty should be visible."] },
      { title: "Match each claim to the right source", text: ["Manufacturer pages and owner manuals are preferred for specifications. Official stores and identifiable Philippine retailers can support current asking-price observations.", "A retailer price does not automatically establish a manufacturer SRP, and a matching tire size does not prove full fitment. The evidence should support the exact claim being made."] },
      { title: "Date changing information", text: ["Prices, offers, regulations and local availability can change. A checked or observed date belongs next to the relevant source.", "Historical launch records remain historical. They should not be silently replaced by current asking prices or presented as a used-bike appraisal."] },
      { title: "Explain filters and estimates", text: ["Budget, displacement, seat height and transmission are objective filters. A recommendation based on them should state the criteria and its limits. Neither low weight nor automatic transmission is a measured safety rating.", "Calculators expose their inputs and formulas. Interest method, term, fees, energy use and reserves should stay visible so a low monthly number cannot hide the total cost."] },
      { title: "Show uncertainty and correct material errors", text: ["Conflicting published prices can be shown as separate observations or a stated range. An estimate must not be described as a test result or manufacturer fact.", "Checked means a dated source is attached. General guidance helps narrow research but is not an exact compatibility guarantee or seller quote. When better evidence establishes an error, the record and source context should be corrected."] },
    ],
  },
  "/data-sources": {
    sourced: true, sections: [
      { title: "Manufacturers and official manuals", text: ["Use manufacturer product pages and exact owner manuals for dimensions, capacities, tire sizes, maintenance and official equipment details.", "An official document still needs to match the motorcycle's generation, trim and market. A technically accurate page for another country can be the wrong source for a Philippine variant."] },
      { title: "Official stores and identifiable retailers", text: ["Current retailer pages can support observed prices, local variants and seller-specific offer information. A quoted asking price is not proof of the manufacturer's universal SRP.", "Record the source, date and conditions. Registration fees, financing terms, battery subscriptions or bundled products can materially change the comparison."] },
      { title: "Government sources for rules", text: ["Use current LTO references for vehicle and license requirements, DTI-BPS for product-conformity guidance and Insurance Commission sources for regulated insurance context.", "The guide should link the agency and retain its checked context. The agency handling the transaction remains the final source for current requirements and assessments."] },
      { title: "Historical publications and archived launch records", text: ["Established publications and archived manufacturer announcements can preserve launch prices and discontinued-generation details no longer available on current product pages.", "Label those references as historical. They cannot, on their own, establish today's used-bike market value."] },
      { title: "Marketplaces and rider claims are leads, not proof", text: ["Marketplace listings, forums and rider reports can identify a fact worth checking. They are not enough by themselves for a technical specification, fitment guarantee or verified top-speed claim.", "Open the citations on a model page when you need to verify a changing fact, and keep test results, manufacturer claims and personal reports distinct."] },
    ], sources: [lto, bps, insurance, honda, yamaha, suzuki],
  },
  "/editorial-policy": {
    sourced: true, sections: [
      { title: "The data comes first", text: ["Comparisons and guides should explain their criteria and give readers enough source context to check important facts themselves. MotoIndex avoids declaring a motorcycle best without a measurable reason.", "A larger engine, a lower seat or a lower price is a difference to understand, not an automatic recommendation for every rider."] },
      { title: "Editorial responsibility", text: ["Erwin Valles is the named author and editor for MotoIndex Philippines research and buyer guides. The work covers motorcycle prices, specifications, gear, fitment, maintenance and ownership decisions.", "The exact model and generation matter. Copy should distinguish factual specifications, published observations, planning estimates and editorial interpretation."] },
      { title: "Commercial relationships", text: ["Seller or affiliate relationships must not change recorded specifications, fitment notes or the order of editorial comparisons. A paid placement should be labeled rather than disguised as an independent recommendation.", "Shopee and Lazada shop buttons may use Involve Asia tracking. Commissions, if earned, do not change model order, prices or fitment notes. Marketplace search results are not inventoried or authenticated by MotoIndex.", "This local application does not process sales, approve financing or guarantee inventory. A dealer listing and an editorial comparison are different kinds of information."] },
      { title: "Corrections and material changes", text: ["When a material fact changes, the record and checked context should be updated. A historical launch price stays historical, rather than being silently turned into a current quote.", "If you find a mismatch, identify the exact page, claim, model and supporting source. The local correction tool lets you prepare and download those details; it does not claim to send a report without a connected delivery service."] },
    ],
  },
  "/authors/erwin-valles": {
    sourced: true, sections: [
      { title: "Author and editor", text: ["Erwin Valles is the author and editor behind MotoIndex Philippines. He reviews motorcycle pricing, specifications, riding gear and buyer guides using traceable manufacturer, government and Philippine market references."] },
      { title: "What Erwin covers", text: ["The coverage focuses on decisions Philippine riders make before and after buying: current price references, model specifications, helmets and gear, physical fit, maintenance and running costs.", "Manufacturer and government sources are preferred for specifications and rules. Philippine seller references are used where current local price or availability needs to be checked."] },
      { title: "Editorial principles", text: ["Use the exact model or generation rather than a similar product. Keep changing prices separate from fixed specifications. Show the source when a buyer may need to verify a claim, and correct errors when better evidence becomes available."], checks: ["Exact model and generation identified.", "Changing price and specification claims separated.", "Sources and dates visible for material facts.", "Limitations and estimates clearly labeled."] },
      { title: "Explore the research", text: ["Use the brand guides for a model overview, the comparison pages for trade-offs and the ownership tools for a budget based on your own inputs. Bookmark a useful guide to return to it from your garage."] },
    ],
  },
};