import type { ResearchPage, ArticleBody } from "./content";

export const gapPages: ResearchPage[] = [
  { href: "/recommendations/cruiser-motorcycles-philippines", title: "Cruiser motorcycles in the Philippines", desc: "Compare recorded cruisers by price, displacement and seat height, with rider-fit and ownership trade-offs kept visible.", topic: "guides", icon: "cruiser" },
  { href: "/recommendations/manual-motorcycles-philippines", title: "Manual motorcycles in the Philippines", desc: "Explore geared motorcycles, compare engine and body types, and keep transmission layout separate from riding suitability.", topic: "guides", icon: "naked" },
  { href: "/recommendations/suzuki-scooters-philippines", title: "Suzuki scooters: models and price references", desc: "Access, Avenis, Skydrive and Burgman models in one source-linked shortlist. Compare the exact configuration, published price and everyday riding fit.", topic: "guides", icon: "scooter" },
  { href: "/recommendations/scrambler-motorcycles-philippines", title: "Scrambler-style motorcycles in the Philippines", desc: "A clearly named style-led shortlist. Compare the PG-1, XSR155 and Svartpilen record without treating appearance as off-road capability.", topic: "guides", icon: "adventure" },
  { href: "/guides/types-of-motorcycles", title: "Types of motorcycles: find the right starting point", desc: "Scooters, underbones, nakeds, sport bikes, cruisers, tourers, dual-sports and scramblers explained for Philippine riders.", topic: "guides", icon: "layers" },
  { href: "/guides/scrambler-vs-cafe-racer", title: "Scrambler vs cafe racer: style, purpose and real differences", desc: "Understand the styling terms, compare the hardware and ask better questions before buying a modern classic or modified motorcycle.", topic: "guides", icon: "compare" },
  { href: "/guides/honda-click-generations", title: "Honda Click V1, V2, V3 and V4: check the exact generation", desc: "Seller shorthand is not a specification. Separate Click 125i, the earlier Click 150i and Click 160 before comparing prices or colors.", topic: "guides", icon: "doc" },
  { href: "/guides/yamaha-xmax-300-vs-400", title: "Yamaha XMAX 300 vs 400: which engine is in the Philippine record?", desc: "The local XMAX reference records 292 cc. Do not apply a 400cc keyword, foreign-market listing or toll-road assumption to a different unit.", topic: "guides", icon: "gauge" },
  { href: "/guides/yamaha-r6-price-philippines", title: "Yamaha R6 price in the Philippines: used, import and track-bike context", desc: "Why a current Philippine R6 quote needs model-year and road-registration context, and why an R7 price is not an R6 answer.", topic: "guides", icon: "sport" },
  { href: "/guides/yamaha-tmax-price-philippines", title: "Yamaha TMAX price Philippines: Standard, Tech Max and older generations", desc: "Separate published seller references, historical 530cc models and current configuration checks before comparing TMAX prices.", topic: "guides", icon: "scooter" },
  { href: "/guides/honda-rs150r-price-philippines", title: "Honda RS150R price and used-bike buying guide", desc: "Treat the discontinued RS150R's old price references as historical context, not a current new-bike offer or a used valuation.", topic: "ownership", icon: "underbone" },
];

const typesSource = { label: "Indian Motorcycle: motorcycle category overview", href: "https://www.indianmotorcycle.com/en-us/articles/buying-guides/different-types-of-motorcycles/" };
const sourceCatalog = { label: "MotoIndex Philippine model reference catalog", href: "https://motoindexph.com/motorcycles" };

export const gapEditorial: Record<string, ArticleBody> = {
  "/guides/types-of-motorcycles": {
    originalSource: false,
    takeaways: ["Body style, transmission and engine displacement answer different questions.", "A category narrows the search; it does not predict physical fit or safety.", "Start with your route, budget and ownership support before choosing a look."],
    sections: [
      { title: "Start with the riding, not a category label", text: ["A daily city commute, two-up provincial trip and trail ride ask different things of a motorcycle. Categories describe broad layouts, not a guarantee that every model suits the same rider or surface.", "Think about your actual distance, traffic, passenger, luggage, parking and service access. Then compare the exact model rather than treating one body style as universally best."] },
      { title: "Scooters and underbones", text: ["Scooters commonly use automatic transmissions and bodywork that emphasizes everyday practicality. Compact commuters, maxi-style scooters and larger touring scooters still differ greatly in weight, engine size and storage.", "Underbones use a different frame and body layout. Their clutch and gear-control arrangements vary by model. An underbone label alone does not tell you whether the bike has a hand clutch or a particular gearbox."] },
      { title: "Naked motorcycles and sport bikes", text: ["Naked or roadster motorcycles generally have less enclosing bodywork than fully faired sport bikes. Compare the actual handlebars, foot controls, seat and wind exposure instead of assuming a comfortable riding position from the category.", "Sport bikes emphasize a road- or circuit-oriented layout, often with fairings and a more committed posture. Do not confuse sporty scooter styling with a sport motorcycle's controls, chassis or intended use."] },
      { title: "Cruisers and touring motorcycles", text: ["Cruisers are associated with a lower-seat, style-led road layout, while touring motorcycles prioritize sustained road travel, luggage and passenger needs. Neither label means every model is light or easy to manage.", "A low seat may come with significant mass, long reach to controls or a different foot position. Try stopping, reversing and parking, not only sitting on the motorcycle in a showroom."] },
      { title: "Adventure, dual-sport and off-road", text: ["Adventure motorcycles span road-biased touring layouts and machines with more unpaved-road capability. A dual-sport is intended to bridge road and trail use, while dedicated competition or off-road models may not be road-registerable.", "Inspect the real suspension, tires, weight, clearance and registration status. Adventure bodywork and a tall front fender are not proof of suitability for a route, and ground clearance is not a floodwater wading depth."] },
      { title: "Scrambler and cafe-racer styles", text: ["These names describe design traditions as well as modern product positioning. A scrambler-style roadster can look rugged without being a dedicated trail motorcycle; a cafe-styled model may prioritize a particular aesthetic or posture.", "For modified motorcycles, the quality of the work and the legal documentary status matter more than the styling label. Do not infer brake, tire or frame compatibility from appearance."] },
      { title: "Electric is a power source, not one body type", text: ["Electric two-wheelers also vary in size, format and legal classification. In the Philippines, the seller's e-bike label does not establish registration or license requirements.", "Check the exact LTO classification, battery ownership or subscription, charging arrangement and service support. An energy-cost estimate is only one part of ownership."] },
    ], faqs: [{ q: "Is a scooter a motorcycle?", a: "Scooter usually describes a motorcycle layout, not an exemption from vehicle rules. Confirm the legal classification of the exact unit, especially for electric models." }, { q: "Which category is best for a beginner?", a: "No category guarantees suitability. Manageable controls, real physical fit, weight, training and the intended use are more useful than choosing from a label alone." }],
    sources: [typesSource, sourceCatalog], related: [{ label: "Explore all motorcycle categories", href: "/motorcycles" }, { label: "Find a bike using your own constraints", href: "/finder" }, { label: "Understand electric vehicle classification", href: "/guides/e-bike-vs-motorcycle" }],
  },
  "/guides/scrambler-vs-cafe-racer": {
    originalSource: false,
    takeaways: ["Neither styling term guarantees a particular capability.", "Compare posture, tires and suspension rather than the badge.", "Modified bikes need inspection and documentary checks."],
    sections: [
      { title: "Two styling traditions, not two universal specifications", text: ["Cafe-racer styling is associated with stripped-back road motorcycles and a more sporting visual treatment. Scrambler styling often borrows cues from motorcycles adapted for mixed surfaces, including upright proportions and rugged-looking details.", "Modern production models use these labels broadly. It is better to compare the exact product than assume every scrambler belongs off-road or every cafe racer has the same riding position."] },
      { title: "Look at the hardware behind the style", text: ["Check the wheel and tire specifications, ground clearance, suspension layout, weight and protection. A tread pattern or high-mounted exhaust does not settle whether a motorcycle suits your terrain.", "For road use, look at the controls and ergonomics too. A low handlebar or rearward foot position can change comfort even if two bikes have similar engine size and seat height."] },
      { title: "A modified build needs a closer look", text: ["Ask what changed from the original specification, who performed the work and what supporting records exist. Frame, suspension, wheels, wiring and brakes are not areas where appearance proves compatibility.", "Arrange an independent mechanical inspection where possible. Check the registration and identifiers, and obtain qualified advice on any modification that affects legal road use."], checks: ["Exact base model and generation identified.", "Modifications and installation quality inspected.", "Tire, wheel and brake compatibility checked.", "Registration and identifiers match the actual unit."] },
      { title: "Choose the posture you can live with", text: ["Test reach to the bars, low-speed control and parking effort. Carrying a passenger or luggage may be very different from the solo look in a photograph.", "Budget for restoration or deferred maintenance on an older build. The purchase price should not consume the entire reserve you need to make the motorcycle safe and serviceable."] },
    ], faqs: [{ q: "Can any scrambler ride trails?", a: "No. A scrambler label may describe styling. Check actual equipment, tires, weight, the route and your experience." }, { q: "Is a factory modern classic the same as a custom cafe racer?", a: "No. A factory model has a defined specification, while a custom build may differ substantially. Inspect the actual motorcycle and supporting documents." }],
    sources: [typesSource], related: [{ label: "Compare scrambler-style model records", href: "/recommendations/scrambler-motorcycles-philippines" }, { label: "Explore cafe-style models", href: "/recommendations/cafe-racer-motorcycles-philippines" }, { label: "Used-bike inspection checklist", href: "/used-motorcycles/buying-checklist" }],
  },
  "/guides/honda-click-generations": {
    originalSource: false,
    takeaways: ["V1, V2, V3 and V4 in seller titles are not enough to identify a unit.", "Separate engine family, model year and exact local configuration.", "Click 150i specifications do not automatically belong to Click 160."],
    sections: [
      { title: "Do not let seller shorthand choose the specification", text: ["Philippine searches use several version labels for the Honda Click. They are useful clues, but a V-number in a listing does not establish the official model year, engine, market or brake package.", "Before comparing prices, ask for the exact model designation, registration year, original documents and current unit photographs. Do not silently map an unverified V4 or V5 label to the latest record in a database."] },
      { title: "Start with the model records that can be separated", text: ["This index keeps Click 125i, Click 160 and the earlier Click 150i as distinct records. The reviewed Click 150i archive describes the 2018-2022 Philippine generation and a historical introductory price of PHP 95,900.", "The current Click 160 reference records a 157cc engine and a different price/specification set. Those figures should not be copied onto an older 150i just because the styling or family name is similar."] },
      { title: "Match prices and colors to the actual year and trim", text: ["A dealer's price can refer to a different year, promotion, paint finish or equipment package. Keep a cash quotation separate from finance estimates and added registration charges.", "Color names and graphics can change within a model family. Inspect the actual unit and ask for the finish and variant on the quotation. Do not use a generic digital swatch as a paint guarantee."], checks: ["Exact model and documented generation identified.", "Engine and frame identifiers matched to OR/CR for a used unit.", "Trim and brake package confirmed.", "Color, fees and battery or accessory inclusions stated in the quote."] },
      { title: "Choose a documented generation", text: ["A family guide keeps the verified models together without mixing their facts. Start there if a listing uses an unfamiliar version name, then open the exact generation that matches the motorcycle you are considering.", "A new-looking panel or a seller's version number is not proof of a new engine or equipment package. Ask for the official model details and documents before interpreting the label as an upgrade."] },
    ], faqs: [{ q: "Does Click V4 always mean the same motorcycle?", a: "Do not assume that from a seller or search label alone. Verify the exact model, local model year, engine and equipment against documents and manufacturer information." }, { q: "Can I compare the old Click 150i launch price with today's Click 160 offer?", a: "Only with the historical versus current context explicit. An old launch price is not a current used-bike valuation or a present-day dealer quote." }],
    sources: [{ label: "MotoIndex Click family and generation context", href: "https://motoindexph.com/motorcycles/honda/click" }, { label: "Honda Click 150i historical reference", href: "https://motoindexph.com/motorcycles/honda/click-150i" }], related: [{ label: "Explore the Click family", href: "/motorcycles/honda/click" }, { label: "Click 125i color reference", href: "/motorcycles/honda/click-125i/colors" }, { label: "Compare Click 125i and Click 160", href: "/compare/click-125i-vs-click-160" }],
  },
  "/guides/yamaha-xmax-300-vs-400": {
    originalSource: false,
    takeaways: ["The Philippine XMAX reference in this index is 292 cc.", "A 300-class name is not an exact displacement figure.", "Do not use a 400cc search term or another market's listing to infer toll-road eligibility."],
    sections: [
      { title: "Which XMAX is described here?", text: ["The Philippine XMAX record in this index describes a 292cc automatic scooter. A May 5, 2025 Philippine news report on the updated XMAX also identifies the 292cc engine and a PHP 311,000 price reference.", "That is not a specification for every XMAX sold in every country or year. A search for XMAX 400 does not turn the recorded local model into a 400cc motorcycle."] },
      { title: "Keep marketing classes and measured displacement separate", text: ["Model names and engine classes are not always exact displacement. Use the manufacturer's actual cubic-capacity specification and the registered unit details rather than reading a number from a listing title.", "If a seller offers a different imported or earlier XMAX version, ask for its exact market, model year, documents and equipment. Treat it as a different record until the facts are established."] },
      { title: "Do not transfer expressway assumptions", text: ["A different engine class or a familiar family name is not proof of permission to use a particular toll road. Check the actual registered motorcycle and the current operator rules.", "Do not use another rider's claim, a foreign-market product page or a broadly worded competitor result to settle that question. A route-dependent legal decision needs current, relevant evidence."] },
      { title: "Compare the ownership package you will receive", text: ["The 2025 report describes changes to convenience equipment such as the windscreen and instruments while keeping the 292cc engine. Similar engine data does not prove that every year has identical features.", "Match a dealer quote to the actual variant, year and equipment. Then compare price, running costs, service support and physical fit before paying a reservation."] },
    ], faqs: [{ q: "Is the local XMAX in this record 400cc?", a: "No. The cited Philippine record and 2025 report describe a 292cc engine. Verify a different unit separately." }, { q: "Should XMAX 300 and XMAX 400 searches use identical specs?", a: "No. A query variation cannot establish that the same product is meant. The exact model, market and generation need identification first." }],
    sources: [{ label: "Zigwheels: updated Philippine XMAX, May 5, 2025", href: "https://www.zigwheels.ph/motorcycle-news/yamaha-motor-ph-quietly-brings-in-updated-xmax" }], related: [{ label: "XMAX model details", href: "/motorcycles/yamaha/xmax" }, { label: "Compare recorded maxi scooters", href: "/recommendations/maxi-scooters-philippines" }, { label: "Plan the ownership cost", href: "/ownership/cost-calculator" }],
  },
  "/guides/yamaha-r6-price-philippines": {
    originalSource: false,
    takeaways: ["No verified current official Philippine R6 SRP is asserted on this page.", "Road-going used R6s and track-only R6 RACE products are different transactions.", "An R7 quotation is not a substitute for an R6 price."],
    sections: [
      { title: "Why a single current R6 price would be misleading", text: ["An R6 search can mean a used road-registered motorcycle, a privately imported unit, or a track-only racing product. Those are not equivalent products or purchase conditions.", "This research did not establish a current official Philippine new-bike R6 SRP. Rather than insert another model's price or invent an offer, this page explains the distinctions needed for a valid quotation."] },
      { title: "Understand the R6 RACE distinction", text: ["Yamaha Motor Europe announced track-only R6 RACE and R6 GYTR models for 2022. Its announcement describes them as non-homologated products and identifies a 599cc engine for the R6 RACE.", "That European product information explains the track-versus-road distinction. It does not establish Philippine availability, import cost, road-registration approval or a current local retail price."] },
      { title: "What a useful Philippine quotation should contain", text: ["For a used motorcycle, request the actual model year, exact unit, asking price, ownership records and service history. For an imported or track product, ask about the seller's authority, delivery terms, documentary status and intended use.", "Do not assume a motorcycle can be registered for public-road use because another R6 once could. Confirm the specific transaction and unit with the appropriate agency and qualified adviser."], checks: ["Road-going or track-only product clearly identified.", "Model year, origin and exact unit confirmed.", "Documentary and registration status independently checked.", "Inspection, parts and service budget included."] },
      { title: "Why the R7 is not the answer to every R6 query", text: ["A competitor page may rank for an R6 phrase while linking to an R7. That is a keyword overlap, not evidence that their engine, purpose or pricing are interchangeable.", "Compare an R7 as a separate alternative if it suits the rider's use. Keep its published price and specification attached to the R7 record instead of labeling it an R6 offer."] },
      { title: "Look beyond the sale price", text: ["Inspection, tires, service, registration, insurance, transport and any track preparation may materially change the first-year budget. For an older performance motorcycle, condition and maintenance history deserve particular attention.", "Get specialist mechanical advice before purchasing a used or modified unit. A polished photograph or a low payment does not establish condition, authenticity or suitability."] },
    ], faqs: [{ q: "What is the current Yamaha R6 SRP in the Philippines?", a: "A current official Philippine SRP was not verified in this research. Obtain a written quote for the exact road-going used, import or track-only product instead of relying on a generic price." }, { q: "Is the R6 RACE automatically road-registerable?", a: "No such claim is made. Yamaha's cited European announcement describes its R6 RACE and GYTR offerings as track-only and non-homologated. Local registration needs separate verification." }],
    sources: [{ label: "Yamaha Motor Europe: track-only R6 RACE and R6 GYTR announcement", href: "https://www.yamaha-motor.eu/gb/en/news/2021/yamaha-announce-two-track-only-r6-models-for-2022--r6-race-and-r/" }, { label: "Yamaha Australia: R6 RACE product description", href: "https://www.yamaha-motor.com.au/products/motorcycle/road/supersport/yzf-r6" }], related: [{ label: "Research the YZF-R7 separately", href: "/motorcycles/yamaha/yzf-r7" }, { label: "Used motorcycle inspection guide", href: "/used-motorcycles/buying-checklist" }, { label: "Explore Yamaha's local model records", href: "/motorcycles/yamaha" }],
  },
  "/guides/yamaha-tmax-price-philippines": {
    originalSource: false,
    takeaways: ["Keep Standard, Tech Max and older generations separate.", "Published comparison-site prices are not dealer quotations.", "Source discrepancies should stay visible, not be averaged away."],
    sections: [
      { title: "The published price references found", text: ["The reviewed Zigwheels TMAX listing gives PHP 779,000 for its Standard reference. A separate Carmudi TMAX Techmax listing gives PHP 849,000. These are different listing records, not proof that every dealer currently stocks either at that price.", "Request a written local quotation for the exact model year and trim. Confirm whether taxes, registration, processing, accessories or delivery are included before comparing totals."] },
      { title: "Do not mix in the 2019 launch reference", text: ["Top Gear's 2019 TMAX entry records PHP 649,000 and a 530cc twin-cylinder engine. That is historical context, not a current new-bike quotation for a later TMAX.", "A used 530cc model and a newer model should be compared on actual unit condition, generation, features and seller price. The old launch SRP is not a used appraisal."] },
      { title: "There is a displacement inconsistency to resolve", text: ["The reviewed Zigwheels page uses 562cc in its specification table and 560cc in portions of its explanatory text. This page does not silently decide which label identifies a particular dealer unit.", "Use the exact manufacturer's specification and registration details for the model year being offered. A competitor's internally inconsistent copy is a reason to verify the record, not repeat every number as a fact."] },
      { title: "Standard and Tech Max equipment needs its own check", text: ["A trim name can signal different equipment, but features change by model year and market. Compare the actual windscreen, instruments, electronics, controls and warranty that the quoted unit includes.", "For a premium maxi scooter, also test low-speed maneuvering, parking, reach to the controls and loading. A comfortable-looking step-through layout does not mean every rider can manage the weight easily."] },
      { title: "Plan ownership before financing", text: ["Budget tires, scheduled maintenance, insurance, registration and service access separately from the purchase price. Use the loan calculator with an actual dealer quote, not the example monthly payment displayed on an unrelated listing.", "Consider the XMAX, Burgman or X-ADV only as separate alternatives with their own engine and price records. None should inherit TMAX specifications merely because the layout is similar."] },
    ], faqs: [{ q: "Is PHP 649,000 today's TMAX price?", a: "That figure belongs to the cited 2019 530cc reference. It must not be presented as a current quote for a later model." }, { q: "Are Standard and Tech Max the same price record?", a: "No. The reviewed listings attach PHP 779,000 and PHP 849,000 to different product records. Confirm generation, equipment and today's actual seller offer." }],
    sources: [{ label: "Zigwheels TMAX Standard price and specification listing", href: "https://www.zigwheels.ph/new-motorcycles/yamaha/tmax" }, { label: "Carmudi TMAX Techmax listing", href: "https://www.carmudi.com.ph/new-motorcycles/yamaha-tmax-techmax/" }, { label: "Top Gear 2019 Yamaha TMAX reference", href: "https://www.topgear.com.ph/buyers-guide/motorcycles/yamaha/tmax" }], related: [{ label: "Explore recorded maxi scooters", href: "/recommendations/maxi-scooters-philippines" }, { label: "Use a real quote in the loan planner", href: "/tools/motorcycle-loan-calculator" }, { label: "Understand XMAX engine-size context", href: "/guides/yamaha-xmax-300-vs-400" }],
  },
  "/guides/honda-rs150r-price-philippines": {
    originalSource: false,
    takeaways: ["The cited RS150R listing labels the model discontinued.", "Old variant prices are not current used-bike valuations.", "Keep RS150R, Winner X and RS125 records separate."],
    sections: [
      { title: "Read the status before the headline price", text: ["The reviewed Zigwheels and Carmudi RS150R records identify the model as discontinued or no longer in production. A dynamically labeled current-year page title should not override that status note.", "The cited price page lists PHP 96,500-97,300 across older variants. Treat those as published historical listing references, not confirmation of a new-bike offer today."] },
      { title: "Identify the exact unit", text: ["The RS150R is a geared underbone, distinct from other RS-named motorcycles and the newer Winner X. Check the actual model designation, year and documents rather than interpreting RS 150 as a complete specification.", "The reviewed record describes a six-speed manual transmission, liquid cooling, approximately 150cc displacement and 13.5 Nm torque. Verify exact specifications and equipment for the unit offered, especially after modifications."] },
      { title: "Build the used-bike budget from evidence", text: ["Ask for the seller's actual price, service history and inspection. Deferred tire, chain, sprocket, fluid or brake work can reduce the apparent saving from a cheap listing.", "An old SRP cannot establish fair market value. Compare equivalent local units with the same model year, paperwork, mileage and condition rather than applying a generic depreciation percentage."] },
      { title: "Check the documentary and mechanical history", text: ["Match identifiers and seller authority to the OR/CR and transaction documents. Check the current transfer requirements, any encumbrance and the release terms before paying.", "Have the motorcycle inspected by a qualified technician. Do not infer compatibility or condition from a racing-style appearance, aftermarket part or seller description."], checks: ["RS150R identity and exact year established.", "Engine and frame identifiers matched to documents.", "Service and modification history reviewed.", "Repair and transfer costs included in the budget."] },
      { title: "Compare a current alternative separately", text: ["Winner X and Sniper 155 can be separate current research choices, but their prices and equipment do not belong to an RS150R. Use the existing model and comparison pages for those alternatives.", "Keep the final decision based on the actual motorcycle, lawful documentary status, usable service support and a price you can verify."] },
    ], faqs: [{ q: "Is the old RS150R price a current dealer offer?", a: "No. The cited listings label the model discontinued. Current availability, any leftover stock or a used asking price must be established for an actual unit." }, { q: "Does an RS150R query mean the Winner X?", a: "No. They are different model records. A competitor ranking an alternative does not justify replacing the requested model's facts with that alternative." }],
    sources: [{ label: "Zigwheels RS150R status and specifications", href: "https://www.zigwheels.ph/new-motorcycles/honda/rs150r" }, { label: "Carmudi RS150R historical variant price references", href: "https://www.carmudi.com.ph/new-motorcycles/honda/rs150r/price/" }], related: [{ label: "Used-bike inspection checklist", href: "/used-motorcycles/buying-checklist" }, { label: "Compare Winner X and Sniper 155 separately", href: "/compare/winner-x-vs-sniper-155" }, { label: "Ownership-transfer guidance", href: "/ownership/transfer-of-ownership" }],
  },
};